config/routes.rb
Rails.application.routes.draw do
  post '/touch', to: 'touch#create', as: 'touch'

  # Sessions
  get    'login',    to: 'sessions#new',     as: 'login'
  post   'sessions', to: 'sessions#create',  as: 'sessions'
  delete 'logout',   to: 'sessions#destroy', as: 'logout'

  resources :settings, only: [:index, :show, :edit, :update]

  resources :benefits

  resources :opening_interviews
  resources :closing_interviews

  resources :risk_assessments do
    member do
      get :fetch_item
      get :new_item
      get :add_items
      patch :sort_by_risk
      post :merge_to_plan
    end

    collection do
      get :auto_complete_for_business_unit
      get :auto_complete_for_business_unit_type
      get :auto_complete_for_best_practice
    end
  end

  resources :risk_assessment_templates

  resources :readings, only: [:create]

  resources :documents do
    get :download, on: :member
    get :auto_complete_for_tagging, on: :collection
  end

  resources :questionnaires do
    resources :polls, only: [:index]
  end

  namespace :polls do
    resources :questionnaires, only: [:index]
    resources :answers, only: [:index]
    resources :business_units, only: [:index]
    resources :users, only: [:index]
  end

  resources :polls do
    collection do
      get :reports
      get :auto_complete_for_business_unit
    end
  end

  resources :e_mails, only: [:index, :show]

  resources :business_unit_types

  resources :groups

  resources :tags, only: [] do
    resources :documents, only: [:index]
  end

  scope ':kind', kind: /control_objective|document|finding|news|plan_item|review/ do
    resources :tags
  end

  resources :news do
    get :auto_complete_for_tagging, on: :collection
  end

  get 'welcome', as: 'welcome', to: 'welcome#index'
  get 'execution_reports', as: 'execution_reports', to: 'execution_reports#index'

  [
    'weaknesses_by_state_execution',
    'weaknesses_report',
    'detailed_management_report',
    'planned_cost_summary',
    'reviews_with_incomplete_work_papers_report'
  ].each do |action|
    get "execution_reports/#{action}", to: "execution_reports##{action}", as: action
  end

  [
    'create_weaknesses_by_state_execution',
    'create_detailed_management_report',
    'create_planned_cost_summary',
    'create_weaknesses_report'
  ].each do |action|
    post "execution_reports/#{action}", to: "execution_reports##{action}", as: action
  end

  %w[
    tagged_findings_report
  ].each do |action|
    get "execution_reports/#{action}", to: "execution_reports##{action}"
    post "execution_reports/create_#{action}", to: "execution_reports#create_#{action}"
  end

  resources :versions, only: [:index, :show]

  resources :notifications, only: [:index, :show, :edit, :update] do
    member do
      get :confirm
    end
  end

  get 'conclusion_reports', as: 'conclusion_reports', to: 'conclusion_reports#index'
  get 'follow_up_audit', as: 'follow_up_audit', to: 'follow_up_audit#index'

  [
    'synthesis_report',
    'review_stats_report',
    'review_scores_report',
    'review_score_details_report',
    'weaknesses_by_state',
    'weaknesses_by_risk',
    'weaknesses_by_risk_and_business_unit',
    'weaknesses_by_audit_type',
    'control_objective_stats',
    'control_objective_stats_by_review',
    'benefits',
    'process_control_stats',
    'qa_indicators',
    'weaknesses_by_business_unit',
    'weaknesses_by_month',
    'weaknesses_by_risk_report',
    'weaknesses_by_user',
    'weaknesses_current_situation',
    'fixed_weaknesses_report',
    'weaknesses_graphs',
    'auto_complete_for_business_unit',
    'auto_complete_for_process_control'
  ].each do |action|
    get "conclusion_reports/#{action}",
      as: "#{action}_conclusion_reports",
      to: "conclusion_reports##{action}"
    get "follow_up_audit/#{action}",
      as: "#{action}_follow_up_audit",
      to: "follow_up_audit##{action}"
  end

  [
    'create_synthesis_report',
    'create_review_stats_report',
    'create_review_scores_report',
    'create_review_score_details_report',
    'create_weaknesses_by_state',
    'create_weaknesses_by_risk',
    'create_weaknesses_by_risk_and_business_unit',
    'create_weaknesses_by_audit_type',
    'create_control_objective_stats',
    'create_control_objective_stats_by_review',
    'create_benefits',
    'create_process_control_stats',
    'create_qa_indicators',
    'create_weaknesses_by_business_unit',
    'create_weaknesses_by_month',
    'create_weaknesses_by_risk_report',
    'create_weaknesses_by_user',
    'create_weaknesses_current_situation',
    'create_fixed_weaknesses_report'
  ].each do |action|
    post "conclusion_reports/#{action}",
      as: "#{action}_conclusion_reports",
      to: "conclusion_reports##{action}"
    post "follow_up_audit/#{action}",
      as: "#{action}_follow_up_audit",
      to: "follow_up_audit##{action}"
  end

  get 'conclusion_reports/cost_analysis',
    as: 'cost_analysis_conclusion_reports',
    to: 'conclusion_reports#cost_analysis'
  post 'conclusion_reports/create_cost_analysis',
    as: 'create_cost_analysis_conclusion_reports',
    to: 'conclusion_reports#create_cost_analysis'
  get 'conclusion_reports/cost_analysis/detailed',
    as: 'detailed_cost_analysis_conclusion_reports',
    to: 'conclusion_reports#cost_analysis',
    include_details: 1

  get 'conclusion_reports/cost_summary',
    as: 'cost_summary_conclusion_reports',
    to: 'conclusion_reports#cost_summary'
  post 'conclusion_reports/create_cost_summary',
    as: 'create_cost_summary_conclusion_reports',
    to: 'conclusion_reports#create_cost_summary'

  %w[
    follow_up_cost_analysis
    weaknesses_report
    weaknesses_evolution
    weaknesses_list
    weaknesses_brief
    tagged_findings_report
  ].each do |action|
    get "follow_up_audit/#{action}",
      as: "#{action}_follow_up_audit",
      to: "follow_up_audit##{action}"
    post "follow_up_audit/create_#{action}",
      as: "create_#{action}_follow_up_audit",
      to: "follow_up_audit#create_#{action}"
  end

  scope ':completed', completed: /complete|incomplete/ do
    resources :findings, except: [:destroy] do
      resources :costs

      get :follow_up_pdf, on: :member, to: 'findings/follow_up_pdf#show'

      collection do
        get :export_to_pdf
        get :export_to_csv
        get :auto_complete_for_tagging
        get :auto_complete_for_finding_relation
      end
    end
  end

  namespace :workflows do
    resources :users, only: [:index]
  end

  resources :workflows do
    get :export_to_pdf, on: :member

    collection do
      get :estimated_amount
      get :reviews_for_period
    end
  end

  namespace :conclusion_draft_reviews do
    resources :users, only: [:index]
  end

  resources :conclusion_draft_reviews, except: [:destroy] do
    member do
      get :export_to_pdf
      get :compose_email
      patch :send_by_email
      get :download_work_papers
      get :score_sheet
      post :create_bundle
    end

    collection do
      get :check_for_approval
      get :corrective_actions_update
    end
  end

  namespace :conclusion_final_reviews do
    resources :users, only: [:index]
  end

  resources :conclusion_final_reviews do
    member do
      get :export_to_pdf
      get :compose_email
      patch :send_by_email
      get :download_work_papers
      get :score_sheet
      post :create_bundle
    end

    get :export_list_to_pdf, on: :collection
  end

  namespace :reviews do
    resources :users, only: [:index]
  end

  resources :reviews do
    member do
      get :survey_pdf
      get :suggested_findings
      get :suggested_process_control_findings
      get :past_implemented_audited_findings
      get :weaknesses_and_oportunities
      get :download_work_papers
      get :estimated_amount
      get :excluded_control_objectives
      patch :finished_work_papers
      patch :recode_findings
      patch :recode_weaknesses_by_risk
      patch :recode_weaknesses_by_repetition_and_risk
      patch :recode_weaknesses_by_control_objective_order
      patch :reorder
      patch :reset_control_objective_name
    end

    collection do
      get :estimated_amount
      get :plan_item_refresh
      get :assignment_type_refresh
      get :plan_item_data
      get :auto_complete_for_finding
      get :auto_complete_for_best_practice
      get :auto_complete_for_process_control
      get :auto_complete_for_control_objective
      get :auto_complete_for_tagging
      get :next_identification_number
    end
  end

  namespace :weaknesses do
    resources :users, only: [:index]
  end

  resources :weaknesses, except: [:destroy] do
    resources :costs

    collection do
      get :auto_complete_for_tagging
      get :auto_complete_for_finding_relation
      get :auto_complete_for_control_objective_item
      get :auto_complete_for_weakness_template
      get :state_changed
      get :weakness_template_changed
    end

    member do
      patch :undo_reiteration
    end
  end

  resources :weakness_templates do
    get :auto_complete_for_control_objective, on: :collection
  end

  resources :control_objective_items do
    get :suggest_next_work_paper_code, on: :member

    collection do
      get :auto_complete_for_business_unit
      get :auto_complete_for_business_unit_type
    end
  end

  namespace :plans do
    resources :users, only: [:index]
  end

  resources :plans do
    resources :plan_items, only: [:new, :edit]

    member do
      get :calendar, to: 'plans/calendar#show'
      get :resources, to: 'plans/resources#show'
      get :stats, to: 'plans/stats#show'
    end

    collection do
      get :auto_complete_for_business_unit
      get :auto_complete_for_tagging
    end
  end

  resources :resource_classes

  resources :control_objectives, only: [:index, :show]

  resources :best_practices do
    resources :process_controls, only: [:new, :edit]

    resources :control_objectives, only: [] do
      get :download, on: :member, controller: 'best_practices/control_objectives'

app/models/best_practice.rb
class BestPractice < ApplicationRecord
  include Auditable
  include BestPractices::AttributeTypes
  include BestPractices::Defaults
  include BestPractices::DestroyValidation
  include BestPractices::JSON
  include BestPractices::ProcessControls
  include BestPractices::Search
  include BestPractices::Shared
  include BestPractices::Validations
  include ParameterSelector
  include Shareable

  belongs_to :group
  belongs_to :organization
end

app/models/concerns/best_practices/attribute_types.rb
module BestPractices::AttributeTypes
  extend ActiveSupport::Concern

  included do
    attribute :obsolete, :boolean
    attribute :shared, :boolean
  end
end

app/models/concerns/best_practices/defaults.rb
module BestPractices::Defaults
  extend ActiveSupport::Concern

  included do
    after_initialize :set_defaults, if: :new_record?
  end

  private

    def set_defaults
      self.group_id        = Current.group&.id
      self.organization_id = Current.organization&.id
    end
end

app/models/concerns/best_practices/destroy_validation.rb
module BestPractices::DestroyValidation
  extend ActiveSupport::Concern

  included do
    before_destroy :check_if_can_be_destroyed
  end

  # Warning: must be public method
  def can_be_destroyed?
    if process_controls.all?(&:can_be_destroyed?)
      true
    else
      errors.add :base, :invalid

      false
    end
  end

  private

    def check_if_can_be_destroyed
      throw :abort unless can_be_destroyed?
    end
end

app/controllers/best_practices/control_objectives_controller.rb
class BestPractices::ControlObjectivesController < ApplicationController
  respond_to :html

  before_action :auth
  before_action :set_best_practice, :set_control_objective, only: [:download]

  def download
    flash[:allow_path] = @control_objective.support&.path

    redirect_to @control_objective.support&.url || root_url
  end

  private

    def set_best_practice
      @best_practice = BestPractice.list.find params[:best_practice_id]
    end

    def set_control_objective
      @control_objective = @best_practice.control_objectives.find params[:id]
    end
end

app/controllers/best_practices_controller.rb
class BestPracticesController < ApplicationController
  include AutoCompleteFor::Tagging

  respond_to :html

  before_action :auth, :load_privileges, :check_privileges
  before_action :set_best_practice, only: [:show, :edit, :update, :destroy]
  before_action :set_title, except: :destroy

  # * GET /best_practices
  def index
    build_search_conditions BestPractice

    @best_practices = BestPractice.list.where(@conditions).reorder(
      obsolete: :asc, name: :asc
    ).page(params[:page])
  end

  # * GET /best_practices/1
  def show
    respond_with @best_practice
  end

  # * GET /best_practices/new
  def new
    @best_practice = BestPractice.new
  end

  # * GET /best_practices/1/edit
  def edit
  end

  # * POST /best_practices
  def create
    @best_practice = BestPractice.new best_practice_params

    @best_practice.save
    respond_with @best_practice, location: edit_best_practice_url(@best_practice)
  end

  # * PATCH /best_practices/1
  def update
    update_resource @best_practice, best_practice_params

    unless response_body
      respond_with @best_practice, location: edit_best_practice_url(@best_practice)
    end
  end

  # * DELETE /best_practices/1
  def destroy
    @best_practice.destroy

    respond_with @best_practice, location: best_practices_url
  end

  private

    def set_best_practice
      @best_practice = BestPractice.list.includes({
        process_controls: :control_objectives
      }).find params[:id]
    end

    def best_practice_params
      params.require(:best_practice).permit(
        :name, :description, :obsolete, :shared, :lock_version,
        process_controls_attributes: [
          :id, :name, :order, :obsolete, :_destroy,
          control_objectives_attributes: [
            :id, :name, :relevance, :risk, :obsolete, :support, :support_cache, :order, :_destroy,
            taggings_attributes: [:id, :tag_id, :_destroy],
            control_attributes:  [
              :id, :control, :effects, :design_tests, :compliance_tests, :sustantive_tests, :_destroy,
            ]
          ]
        ]
      )
    end

    def load_privileges
      @action_privileges.update auto_complete_for_tagging: :read
    end
end

app/controllers/concerns/auto_complete_for/best_practice.rb
module AutoCompleteFor::BestPractice
  extend ActiveSupport::Concern

  def auto_complete_for_best_practice
    @tokens = params[:q][0..100].split(/[\s,]/).uniq
    @tokens.reject! {|t| t.blank?}

    conditions = [
      [
        [
          "#{::BestPractice.table_name}.#{::BestPractice.qcn 'shared'} = :false",
          "#{::BestPractice.table_name}.#{::BestPractice.qcn 'organization_id'} = :organization_id"
        ].join(' AND '),
        [
          "#{::BestPractice.table_name}.#{::BestPractice.qcn 'shared'} = :true",
          "#{::BestPractice.table_name}.#{::BestPractice.qcn 'group_id'} = :group_id"
        ].join(' AND ')
      ].map { |c| "(#{c})" }.join(' OR '),
      "#{::BestPractice.quoted_table_name}.#{::BestPractice.qcn('obsolete')} = :false"
    ]
    parameters = {
      false:           false,
      true:            true,
      organization_id: Current.organization&.id,
      group_id:        Current.group&.id
    }

    @tokens.each_with_index do |t, i|
      conditions << [
        "LOWER(#{::BestPractice.quoted_table_name}.#{::BestPractice.qcn('name')}) LIKE :best_practice_data_#{i}",
      ].join(' OR ')

      parameters[:"best_practice_data_#{i}"] = "%#{t.mb_chars.downcase}%"
    end

    @best_practice = ::BestPractice.where(
      conditions.map { |c| "(#{c})" }.join(' AND '), parameters
    ).order(
      Arel.sql("#{::BestPractice.quoted_table_name}.#{::BestPractice.qcn('name')} ASC")
    ).limit(10)

    respond_to do |format|
      format.json { render json: @best_practice }
    end
  end
end

app/helpers/best_practices/control_objectives_helper.rb
module BestPractices::ControlObjectivesHelper
end

app/helpers/best_practices_helper.rb
module BestPracticesHelper
  def nested_process_controls
    @best_practice.process_controls.build if @best_practice.process_controls.blank?

    @best_practice.process_controls
  end

  def best_practice_shared_icon best_practice
    if best_practice.shared
      title = [
        BestPractice.human_attribute_name('shared'),
        "(#{best_practice.organization.name})"
      ].join ' '

      content_tag :span, nil, class: 'glyphicon glyphicon-eye-open', title: title
    end
  end

  def process_control_path process_control
    if process_control.persisted?
      edit_best_practice_process_control_path @best_practice, process_control
    else
      new_best_practice_process_control_path @best_practice
    end
  end

  def should_fetch_control_objectives_for? process_control
    is_valid = process_control.errors.empty?
    control_objectives_are_unchanged = process_control.control_objectives.all? do |co|
      co.persisted? && co.errors.empty? && !co.changed?
    end

    is_valid && control_objectives_are_unchanged
  end

  def link_to_download_support control_objective, options = {}
    if control_objective.support? && control_objective.support.present?
      best_practice   = control_objective.best_practice
      default_options = {
        class: 'btn btn-default btn-sm',
        title: control_objective.identifier.titleize,
        data:  { ignore_unsaved_data: true }
      }.merge(options)

      link_to download_best_practice_control_objective_path(best_practice, control_objective), default_options do
        content_tag(:span, nil, class: 'icon glyphicon glyphicon-download-alt')
      end
    end
  end
end

app/views/best_practices/_control_objective.html.erb
<% id = f.object.object_id %>
<% process_control_id = process_control_id %>
<fieldset class="control_objective">
  <div class="form-inputs">
    <div class="row">
      <div class="col-md-5">
        <%= f.input :name, autofocus: true, input_html: { rows: 4 } %>
      </div>

      <div class="col-md-2">
        <%= f.input :relevance, collection: relevances, prompt: true %>
      </div>
      <div class="col-md-2">
        <%= f.input :risk, collection: risks, prompt: true %>
      </div>
      <div class="col-md-1">
        <label for="control_objective_continuous_<%= id %>">
          <%= ControlObjective.human_attribute_name 'continuous' %>
        </label>
        <div>
          <%= f.check_box :continuous, id: "control_objective_continuous_#{id}", disabled: f.object.continuous %>
        </div>
      </div>
      <div class="col-md-1">
        <label for="control_objective_obsolete_<%= id %>">
          <%= ControlObjective.human_attribute_name 'obsolete' %>
        </label>
        <div>
          <%= f.check_box :obsolete, id: "control_objective_obsolete_#{id}", data: { process_control_id: process_control_id } %>
        </div>
      </div>
      <div class="col-md-1">
        <div class="toggle-visibility">
          <%= f.input :order, as: :hidden, input_html: { class: 'sort_number' } %>
          <%= link_to_insert_field(f) %>
          <span class="text-muted">|</span>
          <%= link_to_remove_nested_item(f) %>
        </div>
      </div>
    </div>

    <div class="row">
      <%= f.simple_fields_for :control do |c_f| %>
        <div class="col-md-3">
          <%= c_f.input :control, input_html: { rows: 4 } %>
        </div>
        <div class="col-md-2">
          <%= c_f.input :design_tests, input_html: { rows: 4 } %>
        </div>
        <div class="col-md-3">
          <%= c_f.input :compliance_tests, input_html: { rows: 4 } %>
        </div>
        <div class="col-md-2">
          <%= c_f.input :sustantive_tests, input_html: { rows: 4 } %>
        </div>
        <div class="col-md-2">
          <%= c_f.input :effects, input_html: { rows: 4 } %>
        </div>
        <%= c_f.input :order, as: :hidden %>
      <% end %>
    </div>
  </div>

  <hr>
</fieldset>
<script type="text/javascript">FormUtil.completeSortNumbers();</script>

app/views/best_practices/_form.html.erb
<%= simple_form_for @best_practice do |f| %>
  <%= render 'shared/error_explanation', f: f %>

  <div class="form-inputs">
    <%= f.input :name, autofocus: true, input_html: { maxlength: 255 } %>
    <%= f.input :description %>
    <%= f.input :obsolete %>
    <%= f.input :shared, input_html: { disabled: @best_practice.shared } %>
  </div>

  <% if @best_practice.persisted? %>
    <div class="row">
      <div class="col-md-10">
        <h5><strong><%= ProcessControl.model_name.human count: 0 %></strong></h5>
      </div>
      <div class="col-md-1">
        <h5><strong><%= ProcessControl.human_attribute_name 'obsolete' %></strong></h5>
      </div>
    </div>

    <div id="process_controls">
      <%= f.simple_fields_for :process_controls, nested_process_controls do |p_f| %>
        <%= render 'process_control', f: p_f %>
      <% end %>

      <%= link_to_add_fields t('best_practices.process_controls.new'), f, :process_controls %>
    </div>
  <% end %>

  <hr />

  <div class="form-actions">
    <%= f.input :organization_id, as: :hidden %>
    <%= f.input :lock_version, as: :hidden %>
    <%= f.submit class: 'btn btn-primary' %>
    <div class="pull-right"><%= yield :form_actions %></div>
  </div>
<% end %>

app/views/best_practices/_process_control.html.erb
<% id    = f.object.object_id %>
<% fetch = should_fetch_control_objectives_for? f.object %>

<fieldset class="process_control">
  <div class="form-inputs row">
    <div class="col-md-10">
      <div class="media">
        <div class="pull-left toggle-visibility">
          <%= link_to_fetch_hide id, fetch ? :fetch : :show %>
        </div>
        <div class="media-body">
          <%= f.input :name, label: false, input_html: { maxlength: 255 } %>
        </div>
      </div>
    </div>
    <div class="col-md-1">
      <%= f.input :obsolete, label: false, input_html: { data: { process_control: f.object.id || id } } %>
    </div>
    <div class="col-md-1 toggle-visibility">
      <%= link_to_insert_field(f) %>
      <span class="text-muted">|</span>
      <%= link_to_remove_nested_item(f) %>
      <%= f.input :id, as: :hidden %>
      <%= f.input :order, as: :hidden, input_html: { class: 'sort_number' } %>
    </div>
  </div>

  <div class="nested hidden">
    <div class="hidden" data-container-id="<%= id %>" data-index="<%= f.index %>" data-url="<%= process_control_path f.object %>">
      <% if fetch %>
        <div class="alert alert-warning">
          <%= t 'navigation.loading' %>
        </div>
      <% else %>
        <%= render 'process_controls/form', process_control: f.object, index: f.index %>
      <% end %>
    </div>

    <%= link_to_add_fields t('best_practices.control_objectives.new'), f, :control_objectives, 'process_controls/control_objective' %>
    <p>&nbsp;</p>
  </div>
</fieldset>

<script type="text/javascript">FormUtil.completeSortNumbers();</script>

app/views/best_practices/edit.html.erb
<%= content_for :form_actions do %>
  <%= link_to_show @best_practice %> |
  <%= link_to_index best_practices_path %>
<% end %>

<%= render 'form' %>

app/views/best_practices/index.html.erb
<%= render partial: 'shared/search', locals: {
  options: {},
  columns: @query.blank? ? BestPractice::COLUMNS_FOR_SEARCH.keys : @columns
} %>
<table class="table table-condensed table-striped table-hover">
  <thead id="column_headers">
    <tr>
      <%= make_filterable_column BestPractice.human_attribute_name('name'), nil, 'name' %>
      <%= make_not_available_column BestPractice.human_attribute_name('description'), { class: 'hidden-xs' } %>
      <th colspan="3" class="text-right"><%= link_to_search %></th>
    </tr>
  </thead>

  <tbody>
    <% @best_practices.each do |best_practice| %>
      <tr <%== 'class="text-muted strike"' if best_practice.obsolete %>>
        <td>
          <%= best_practice_shared_icon best_practice %>
          <%= super_truncate best_practice.name, 40 %>
        </td>
        <td class="hidden-xs"><%= super_truncate(best_practice.description, 40) %></td>
        <td><%= link_to_show best_practice %></td>
        <td><%= link_to_edit edit_best_practice_path(best_practice) %></td>
        <td><%= link_to_destroy best_practice %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr />

<%= paginate @best_practices %>
<%= link_to_new new_best_practice_path, class: 'btn btn-primary' %>

app/views/best_practices/new.html.erb
<%= content_for :form_actions do %>
  <%= link_to_index best_practices_path %>
<% end %>

<%= render 'form' %>

app/views/best_practices/show.html.erb
<div class="page-header">
  <h2><%= BestPractice.model_name.human %>: <%= @best_practice.name %></h2>
</div>

<% @best_practice.process_controls.each do |pc| %>
  <h4><%= "#{@best_practice.name} (#{pc.name})" %></h4>
  <table class="table table-condensed table-striped table-hover">
    <thead>
      <tr>
        <th><%= ControlObjective.human_attribute_name 'name' %></th>
        <th><%= Control.human_attribute_name 'control' %></th>
        <th><%= Control.human_attribute_name 'design_tests' %></th>
        <% unless HIDE_CONTROL_COMPLIANCE_TESTS %>
          <th><%= Control.human_attribute_name 'compliance_tests' %></th>
        <% end %>
        <th><%= Control.human_attribute_name 'sustantive_tests' %></th>
        <% unless HIDE_CONTROL_EFFECTS %>
          <th><%= Control.human_attribute_name 'effects' %></th>
        <% end %>
        <th><%= ControlObjective.human_attribute_name 'risk' %></th>
        <th><%= ControlObjective.human_attribute_name 'support' %></th>
        <th><%= Tag.model_name.human count: 0 %></th>
      </tr>
    </thead>
    <tbody>
      <% pc.control_objectives.each do |co| %>
        <tr <%== 'class="text-muted strike"' if co.obsolete %>>
          <td><%= simple_format co.name %></td>
          <td><%= simple_format co.control.control %></td>
          <td><%= simple_format co.control.design_tests %></td>
          <% unless HIDE_CONTROL_COMPLIANCE_TESTS %>
            <td><%= simple_format co.control.compliance_tests %></td>
          <% end %>
          <td><%= simple_format co.control.sustantive_tests %></td>
          <% unless HIDE_CONTROL_EFFECTS %>
            <td><%= simple_format co.control.effects %></td>
          <% end %>
          <td><%= co.risk_text %></td>
          <td><%= link_to_download_support co %></td>
          <td><%= tags co.tags %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<hr />

<%= link_to_edit edit_best_practice_path(@best_practice) %> |
<%= link_to_index best_practices_path %>