config/routes.rb
Rails.application.routes.draw do
  post '/touch', to: 'touch#create', as: 'touch'

  # Sessions
  get    'login',    to: 'sessions#new',     as: 'login'
  post   'sessions', to: 'sessions#create',  as: 'sessions'
  delete 'logout',   to: 'sessions#destroy', as: 'logout'

  resources :settings, only: [:index, :show, :edit, :update]

  resources :benefits

  resources :opening_interviews
  resources :closing_interviews

  resources :risk_assessments do
    member do
      get :fetch_item
      get :new_item
      get :add_items
      patch :sort_by_risk
      post :merge_to_plan
    end

    collection do
      get :auto_complete_for_business_unit
      get :auto_complete_for_business_unit_type
      get :auto_complete_for_best_practice
    end
  end

  resources :risk_assessment_templates

  resources :readings, only: [:create]

  resources :documents do
    get :download, on: :member
    get :auto_complete_for_tagging, on: :collection
  end

  resources :questionnaires do
    resources :polls, only: [:index]
  end

  namespace :polls do
    resources :questionnaires, only: [:index]
    resources :answers, only: [:index]
    resources :business_units, only: [:index]
    resources :users, only: [:index]
  end

  resources :polls do
    collection do
      get :reports
      get :auto_complete_for_business_unit
    end
  end

  resources :e_mails, only: [:index, :show]

  resources :business_unit_types

  resources :groups

  resources :tags, only: [] do
    resources :documents, only: [:index]
  end

  scope ':kind', kind: /control_objective|document|finding|news|plan_item|review/ do
    resources :tags
  end

  resources :news do
    get :auto_complete_for_tagging, on: :collection
  end

  get 'welcome', as: 'welcome', to: 'welcome#index'
  get 'execution_reports', as: 'execution_reports', to: 'execution_reports#index'

  [
    'weaknesses_by_state_execution',
    'weaknesses_report',
    'detailed_management_report',
    'planned_cost_summary',
    'reviews_with_incomplete_work_papers_report'
  ].each do |action|
    get "execution_reports/#{action}", to: "execution_reports##{action}", as: action
  end

  [
    'create_weaknesses_by_state_execution',
    'create_detailed_management_report',
    'create_planned_cost_summary',
    'create_weaknesses_report'
  ].each do |action|
    post "execution_reports/#{action}", to: "execution_reports##{action}", as: action
  end

  %w[
    tagged_findings_report
  ].each do |action|
    get "execution_reports/#{action}", to: "execution_reports##{action}"
    post "execution_reports/create_#{action}", to: "execution_reports#create_#{action}"
  end

  resources :versions, only: [:index, :show]

  resources :notifications, only: [:index, :show, :edit, :update] do
    member do
      get :confirm
    end
  end

  get 'conclusion_reports', as: 'conclusion_reports', to: 'conclusion_reports#index'
  get 'follow_up_audit', as: 'follow_up_audit', to: 'follow_up_audit#index'

  [
    'synthesis_report',
    'review_stats_report',
    'review_scores_report',
    'review_score_details_report',
    'weaknesses_by_state',
    'weaknesses_by_risk',
    'weaknesses_by_risk_and_business_unit',
    'weaknesses_by_audit_type',
    'control_objective_stats',
    'control_objective_stats_by_review',
    'benefits',
    'process_control_stats',
    'qa_indicators',
    'weaknesses_by_business_unit',
    'weaknesses_by_month',
    'weaknesses_by_risk_report',
    'weaknesses_by_user',
    'weaknesses_current_situation',
    'fixed_weaknesses_report',
    'weaknesses_graphs',
    'auto_complete_for_business_unit',
    'auto_complete_for_process_control'
  ].each do |action|
    get "conclusion_reports/#{action}",
      as: "#{action}_conclusion_reports",
      to: "conclusion_reports##{action}"
    get "follow_up_audit/#{action}",
      as: "#{action}_follow_up_audit",
      to: "follow_up_audit##{action}"
  end

  [
    'create_synthesis_report',
    'create_review_stats_report',
    'create_review_scores_report',
    'create_review_score_details_report',
    'create_weaknesses_by_state',
    'create_weaknesses_by_risk',
    'create_weaknesses_by_risk_and_business_unit',
    'create_weaknesses_by_audit_type',
    'create_control_objective_stats',
    'create_control_objective_stats_by_review',
    'create_benefits',
    'create_process_control_stats',
    'create_qa_indicators',
    'create_weaknesses_by_business_unit',
    'create_weaknesses_by_month',
    'create_weaknesses_by_risk_report',
    'create_weaknesses_by_user',
    'create_weaknesses_current_situation',
    'create_fixed_weaknesses_report'
  ].each do |action|
    post "conclusion_reports/#{action}",
      as: "#{action}_conclusion_reports",
      to: "conclusion_reports##{action}"
    post "follow_up_audit/#{action}",
      as: "#{action}_follow_up_audit",
      to: "follow_up_audit##{action}"
  end

  get 'conclusion_reports/cost_analysis',
    as: 'cost_analysis_conclusion_reports',
    to: 'conclusion_reports#cost_analysis'
  post 'conclusion_reports/create_cost_analysis',
    as: 'create_cost_analysis_conclusion_reports',
    to: 'conclusion_reports#create_cost_analysis'
  get 'conclusion_reports/cost_analysis/detailed',
    as: 'detailed_cost_analysis_conclusion_reports',
    to: 'conclusion_reports#cost_analysis',
    include_details: 1

  get 'conclusion_reports/cost_summary',
    as: 'cost_summary_conclusion_reports',
    to: 'conclusion_reports#cost_summary'
  post 'conclusion_reports/create_cost_summary',
    as: 'create_cost_summary_conclusion_reports',
    to: 'conclusion_reports#create_cost_summary'

  %w[
    follow_up_cost_analysis
    weaknesses_report
    weaknesses_evolution
    weaknesses_list
    weaknesses_brief
    tagged_findings_report
  ].each do |action|
    get "follow_up_audit/#{action}",
      as: "#{action}_follow_up_audit",
      to: "follow_up_audit##{action}"
    post "follow_up_audit/create_#{action}",
      as: "create_#{action}_follow_up_audit",
      to: "follow_up_audit#create_#{action}"
  end

  scope ':completed', completed: /complete|incomplete/ do
    resources :findings, except: [:destroy] do
      resources :costs

      get :follow_up_pdf, on: :member, to: 'findings/follow_up_pdf#show'

      collection do
        get :export_to_pdf
        get :export_to_csv
        get :auto_complete_for_tagging
        get :auto_complete_for_finding_relation
      end
    end
  end

  namespace :workflows do
    resources :users, only: [:index]
  end

  resources :workflows do
    get :export_to_pdf, on: :member

    collection do
      get :estimated_amount
      get :reviews_for_period
    end
  end

  namespace :conclusion_draft_reviews do
    resources :users, only: [:index]
  end

  resources :conclusion_draft_reviews, except: [:destroy] do
    member do
      get :export_to_pdf
      get :compose_email
      patch :send_by_email
      get :download_work_papers
      get :score_sheet
      post :create_bundle
    end

    collection do
      get :check_for_approval
      get :corrective_actions_update
    end
  end

  namespace :conclusion_final_reviews do
    resources :users, only: [:index]
  end

  resources :conclusion_final_reviews do
    member do
      get :export_to_pdf
      get :compose_email
      patch :send_by_email
      get :download_work_papers
      get :score_sheet
      post :create_bundle
    end

    get :export_list_to_pdf, on: :collection
  end

  namespace :reviews do
    resources :users, only: [:index]
  end

  resources :reviews do
    member do
      get :survey_pdf
      get :suggested_findings
      get :suggested_process_control_findings
      get :past_implemented_audited_findings
      get :weaknesses_and_oportunities
      get :download_work_papers
      get :estimated_amount
      get :excluded_control_objectives
      patch :finished_work_papers
      patch :recode_findings
      patch :recode_weaknesses_by_risk
      patch :recode_weaknesses_by_repetition_and_risk
      patch :recode_weaknesses_by_control_objective_order
      patch :reorder
      patch :reset_control_objective_name
    end

    collection do
      get :estimated_amount
      get :plan_item_refresh
      get :assignment_type_refresh
      get :plan_item_data
      get :auto_complete_for_finding
      get :auto_complete_for_best_practice
      get :auto_complete_for_process_control
      get :auto_complete_for_control_objective
      get :auto_complete_for_tagging
      get :next_identification_number
    end
  end

  namespace :weaknesses do
    resources :users, only: [:index]
  end

  resources :weaknesses, except: [:destroy] do
    resources :costs

    collection do
      get :auto_complete_for_tagging
      get :auto_complete_for_finding_relation
      get :auto_complete_for_control_objective_item
      get :auto_complete_for_weakness_template
      get :state_changed
      get :weakness_template_changed
    end

    member do
      patch :undo_reiteration
    end
  end

  resources :weakness_templates do
    get :auto_complete_for_control_objective, on: :collection
  end

  resources :control_objective_items do
    get :suggest_next_work_paper_code, on: :member

    collection do
      get :auto_complete_for_business_unit
      get :auto_complete_for_business_unit_type
    end
  end

  namespace :plans do
    resources :users, only: [:index]
  end

  resources :plans do
    resources :plan_items, only: [:new, :edit]

    member do
      get :calendar, to: 'plans/calendar#show'
      get :resources, to: 'plans/resources#show'
      get :stats, to: 'plans/stats#show'
    end

    collection do
      get :auto_complete_for_business_unit
      get :auto_complete_for_tagging
    end
  end

  resources :resource_classes

  resources :control_objectives, only: [:index, :show]

  resources :best_practices do
    resources :process_controls, only: [:new, :edit]

    resources :control_objectives, only: [] do
      get :download, on: :member, controller: 'best_practices/control_objectives'

app/models/concerns/weaknesses/code.rb
module Weaknesses::Code
  extend ActiveSupport::Concern

  def prefix
    I18n.t 'code_prefixes.weaknesses'
  end

  def next_code review = nil
    review ||= control_objective_item&.review

    review ? review.next_weakness_code(prefix) : "#{prefix}1".strip
  end
end

app/models/concerns/weaknesses/defaults.rb
module Weaknesses::Defaults
  extend ActiveSupport::Concern

  included do
    after_initialize :set_review_code, if: :new_record?
    after_initialize :set_priority, if: -> { HIDE_WEAKNESS_PRIORITY }
    after_initialize :set_progress, if: -> { SHOW_WEAKNESS_PROGRESS }
  end

  private

    def set_review_code
      self.review_code ||= next_code
    end

    def set_priority
      self.priority ||= self.class.priorities_values.first
    end

    def set_progress
      self.progress ||= 0
    end
end

app/models/concerns/weaknesses/priority.rb
module Weaknesses::Priority
  extend ActiveSupport::Concern

  def priority_text
    priority = self.class.priorities.detect { |p| p.last == self.priority }

    priority ? I18n.t("priority_types.#{priority.first}") : ''
  end
end

app/models/role.rb
class Role < ApplicationRecord
  include Auditable
  include Comparable
  include Roles::Scopes
  include ParameterSelector

  # Constantes
  TYPES = {
    :admin => 0,
    :manager => 1,
    :supervisor => 2,
    :auditor_senior => 3,
    :auditor_junior => 4,
    :committee => 5,
    :audited => 6,
    :executive_manager => 7
  }

  ACT_AS = {
    audited: TYPES.slice(:admin, :audited, :executive_manager).values,
    auditor: TYPES.slice(:auditor_senior, :auditor_junior, :supervisor, :manager).values
  }.freeze

  # Callbacks
  before_validation :check_auth_privileges
  before_save :check_change_in_privileges

  # Restricciones
  validates :name, :organization_id, :role_type, :presence => true
  validates :name, :length => {:maximum => 255}, :allow_nil => true,
    :allow_blank => true
  validates :role_type, :inclusion => {:in => TYPES.values}, :allow_nil => true,
    :allow_blank => true
  validates :organization_id, :numericality => {:integer_only => true},
    :allow_nil => true, :allow_blank => true
  validates :name, :uniqueness =>
    {:case_sensitive => false, :scope => :organization_id}

  # Relaciones
  belongs_to :organization
  has_many :organization_roles, :dependent => :destroy
  has_many :privileges, :after_add => :assign_role, :dependent => :destroy
  has_many :users, -> { readonly }, :through => :organization_roles

  accepts_nested_attributes_for :privileges, :allow_destroy => true

  def initialize(attributes = nil)
    super(attributes)

    self.role_type ||= TYPES[:admin]
  end

  def assign_role(privilege)
    privilege.role = self
  end

  def <=>(other)
    other.kind_of?(Role) ? self.role_type <=> other.role_type : -1
  end

  def check_change_in_privileges
    self.touch if !self.new_record? && self.privileges.any?(&:changed?)
  end

  # Definición dinámica de todos los métodos "tipo?"
  TYPES.each do |type, value|
    define_method(:"#{type}?") { self.role_type == value }
  end

  def get_type
    TYPES.invert[self.role_type]
  end

  def allowed_modules
    get_type ? ALLOWED_MODULES_BY_TYPE[get_type] : []
  end

  def inject_auth_privileges(auth_privileges)
    if auth_privileges
      @auth_privileges = Marshal::load(Marshal::dump(auth_privileges))
    end
  end

  def check_auth_privileges
    unless self.has_auth_privileges?
      raise 'Must inject the auth privileges before save a Role'
    end
  end

  def has_auth_privileges?
    !@auth_privileges.nil?
  end

  def auth_privileges_for(module_name)
    module_name = '_' if module_name.blank?

    @auth_privileges[module_name] || @auth_privileges[module_name.to_sym] || {}
  end

  def privileges_hash
    privileges = ActiveSupport::HashWithIndifferentAccess.new

    self.privileges.each do |p|
      privileges[p.module] = {
        :read => p.read?,
        :modify => p.modify?,
        :erase => p.erase?,
        :approval => p.approval?
      }
    end

    privileges
  end

  def has_privilege_for?(module_name)
    self.privileges.any? do |p|
      p.module.to_sym == module_name.to_sym &&
        (p.read? || p.modify? || p.erase? || p.approval?)
    end
  end

  [:read, :modify, :erase, :approval].each do |action|
    define_method :"has_privilege_for_#{action}?" do |module_name|
      self.privileges.any? do |p|
        p.module.to_sym == module_name.to_sym && p.send(:"#{action}?")
      end
    end
  end
end

app/controllers/weaknesses/users_controller.rb
class Weaknesses::UsersController < ApplicationController
  include Users::Searches

  def index
    render template: 'users/index'
  end
end

app/helpers/weaknesses/users_helper.rb
module Weaknesses::UsersHelper
end

app/helpers/weaknesses_helper.rb
module WeaknessesHelper
  def show_weakness_previous_follow_up_dates(weakness)
    list = String.new.html_safe
    out = String.new.html_safe

    if weakness.being_implemented? || weakness.awaiting?
      dates = weakness.all_follow_up_dates
    end

    if dates.present?
      dates.each { |d| list << content_tag(:li, l(d, :format => :long)) }

      out << link_to(t('weakness.previous_follow_up_dates'), '#', :onclick =>
        "$('#previous_follow_up_dates').slideToggle();return false;")

      out << content_tag(:div, content_tag(:ol, list),
        :id => 'previous_follow_up_dates', :style => 'display: none; margin-bottom: 1em;')

      content_tag(:div, out, :style => 'margin-bottom: 1em;')
    end
  end

  def next_weakness_work_paper_code(weakness, follow_up = false)
    review = weakness.control_objective_item.try(:review)
    code_prefix = follow_up ?
      t('code_prefixes.work_papers_in_weaknesses_follow_up') :
      weakness.work_paper_prefix

    code_from_review = review ?
      review.last_weakness_work_paper_code(prefix: code_prefix) :
      "#{code_prefix} 0".strip

    work_paper_codes = weakness.work_papers.reject(
      &:marked_for_destruction?).map(
      &:code).select { |c| c =~ /#{code_prefix}\s\d+/ }

    last_code = work_paper_codes.map do |code|
      code.match(/\d+\Z/)[0].to_i if code =~ /\d+\Z/
    end.compact.sort.last.to_i

    next_number = [code_from_review.match(/\d+\Z/)[0].to_i, last_code].max

    "#{code_prefix} #{next_number}"
  end

  def benefit_exists?
    Benefit.list.exists?
  end

  def weakness_achievements_for kind
    Benefit.list.where(kind: kind).order(created_at: :asc).map do |benefit|
      achievement = @weakness.achievements.detect { |a| a.benefit_id == benefit.id }

      achievement || @weakness.achievements.new(benefit_id: benefit.id)
    end
  end

  def weakness_business_units
    @weakness.control_objective_item.business_units
  end

  def weakness_progresses weakness
    values = if weakness.being_implemented?
               [25, 50, 75]
             else
               [0, 25, 50, 75, 100]
             end

    values.map { |n| ["#{n}%", n] }
  end

  def weakness_progress_disabled? weakness, readonly = false
    readonly || !weakness.allow_progress_edition?
  end

  def weakness_compliance_options
    COMPLIANCE_OPTIONS.map do |option, options|
      [t("label.#{option}"), option, options]
    end
  end

  def weakness_operational_risk_options
    WEAKNESS_OPERATIONAL_RISK.map { |option, options| [option, option, options] }
  end

  def weakness_impact_options
    WEAKNESS_IMPACT.map { |option, options| [option, option, options] }
  end

  def weakness_internal_control_components_options
    WEAKNESS_INTERNAL_CONTROL_COMPONENTS.map { |option| [option, option] }
  end

  def show_weakness_templates?
    @weakness.new_record? &&
      @weakness.weakness_template_id.blank? &&
      WeaknessTemplate.list.any?
  end

  def weakness_templates_for weakness
    control_objective  = weakness.control_objective_item&.control_objective

    control_objective &&
      WeaknessTemplate.list.by_control_objective(control_objective)
  end
end

app/views/weaknesses/_task.html.erb
<%
  id = f.object.object_id
  finding = f.object.finding
  task = f.object
  readonly = readonly
%>
<fieldset class="task">
  <div class="form-inputs">
    <div class="row">
      <div class="col-md-1">
        <%= f.input :code, label: false, input_html: { readonly: true, data: { task_code: true } } %>
      </div>
      <div class="col-md-5">
        <%= f.input :description, label: false, input_html: { autofocus: task.new_record?, rows: 1, readonly: readonly } %>
      </div>
      <div class="col-md-2">
        <%= f.input :status, collection: finding_task_status_options, label: false, prompt: false, input_html: { readonly: readonly } %>
      </div>
      <div class="col-md-2">
        <%= f.input :due_on, as: :date_picker, label: false, input_html: { readonly: readonly, data: { override_follow_up_date: true } } %>
      </div>
      <div class="col-md-1">
        <% if task.due_on && !task.finished? && task.due_on >= Time.zone.today %>
          <% if task.all_due_on_dates.empty? %>
            <span class="text-success" title="<%= t 'tasks.on_time' %>">
              <span class="glyphicon glyphicon-ok"></span>
            </span>
          <% else %>
            <span class="text-warning" title="<%= t 'tasks.rescheduled' %>">
              <span class="glyphicon glyphicon-repeat"></span>
            </span>
          <% end %>
        <% elsif task.due_on && !task.finished? %>
          <span class="text-danger" title="<%= t 'tasks.expired' %>">
            <span class="glyphicon glyphicon-time"></span>
          </span>
        <% end %>
      </div>
      <div class="col-md-1">
        <div class="toggle-visibility">
          <%= f.input :finding_id, as: :hidden %>
          <%= link_to_remove_nested_item(f) unless readonly %>
        </div>
      </div>
    </div>
  </div>
</fieldset>

app/views/weaknesses/_tasks.html.erb
<%= f.simple_fields_for :tasks do |fr_f| %>
  <%= render 'task', f: fr_f, readonly: readonly %>
<% end %>

<%= link_to_add_fields t('finding.add_task'), f, :tasks unless readonly %>

app/views/weaknesses/_user.html.erb
<% id = "#{dynamic_object_id('user', f)}_#{is_dynamic ? 'NEW_RECORD' : user.id}" %>
<% hide = is_dynamic || user.marked_for_destruction? %>
<div class="user item" id="<%= id %>" <%= 'style="display: none;"' if hide %>>
  <div>
    <div class="item_field" style="width: 90%;">
      <% unless readonly %>
        <div class="search">
          <%= hidden_field_tag 'weakness[user_ids][]', user.id,
            :id => "hidden_user_#{id}", :class => :autocomplete_id_item %>
          <%= text_field_with_auto_complete :weakness, :nested_user,
            {:id => "weakness_user_#{id}", :class => :search,
            :title => t(:'label.search'), :value => user.full_name_with_function},
            {:indicator => :loading, :skip_style => true,
            :url => {:action => :auto_complete_for_user},
            :after_update_element => 'AutoComplete.itemSelected',
            :param_name => 'user_data',
            :parameters => ("weakness_id=#{@weakness.id}" unless @weakness.new_record?)} %>
        </div>
      <% else %>
        <%= hidden_field_tag 'weakness[user_ids][]', user.id,
          :id => "hidden_user_#{id}" %>
        <%= text_field_tag "weakness_user_#{id}",
          user.full_name_with_function(f.object.created_at), :readonly => true %>
      <% end %>
    </div>
    <div class="item_field item_controls" style="width: 5%;">
      <%= remove_list_item_link(f) unless readonly %>
    </div>
  </div>
</div>
<% if is_dynamic %>
  <script type="text/javascript">Helper.showItem('<%= id %>');</script>
<% end %>

app/views/weaknesses/_weakness_templates.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title" id="weakness-template-heading">
      <a data-toggle="collapse" href="#weakness-templates" aria-expanded="true" aria-controls="weakness-templates">
        <%= WeaknessTemplate.model_name.human count: 0 %>
      </a>
    </h3>
  </div>
  <div id="weakness-templates" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="weakness-template-heading">
    <div class="panel-body">
      <div class="row">
        <div class="col-md-6">
          <%= f.input :weakness_template_from_control_objective, collection: weakness_templates_for(f.object), prompt: true, input_html: {
            value: f.object.weakness_template_id
          } %>
        </div>
        <div class="col-md-6">
          <%= f.input :weakness_template, input_html: {
            title: t('label.search'),
            autocomplete: :off,
            data: {
              autocomplete_url: auto_complete_for_weakness_template_weaknesses_path,
              autocomplete_id_target: '#weakness_template_id'
            }
          } %>
        </div>
      </div>
      <%= f.input :weakness_template_id, as: :hidden, input_html: {
        id: 'weakness_template_id',
        data: {
          weakness_template_changed_url: weakness_template_changed_weaknesses_path
        }
      } %>
    </div>
  </div>
</div>

app/views/weaknesses/edit.html.erb
<%= content_for :form_actions do %>
  <%= link_to_show @weakness %> |
  <%= link_to_index weaknesses_path %>
  <% if @weakness.control_objective_item %>
    | <%= link_to t('weakness.edit_control_objective'),
      edit_control_objective_item_path(@weakness.control_objective_item) %>
  <% end %>
  <% if !@weakness.is_in_a_final_review? && @weakness.pending? && !@weakness.incomplete? %>
    | <%= link_to t('weakness.edit_follow_up'), edit_finding_path('incomplete', @weakness) %>
  <% end %>
<% end %>

<%= render 'form' %>

app/views/weaknesses/index.html.erb
<% if params[:control_objective].blank? %>
  <%= render :partial => 'shared/search', :locals => {
    :options => {:columns_for_sort => Weakness.columns_for_sort},
    :columns => @query.blank? ? (Weakness::COLUMNS_FOR_SEARCH.keys - ['organization']) : @columns
  } %>
<% end %>
<table class="table table-condensed table-striped table-hover">
  <thead id="column_headers">
    <tr>
      <th></th>
      <%= make_filterable_column Review.model_name.human, nil, 'review' %>
      <%= make_filterable_column PlanItem.human_attribute_name(:project), { :class => 'hidden-xs'}, 'project' %>
      <%= make_filterable_column Weakness.human_attribute_name(:review_code), nil, 'review_code' %>
      <%= make_filterable_column Weakness.human_attribute_name(:title), { :class => 'hidden-xs'}, 'title' %>
      <%= make_not_available_column Weakness.human_attribute_name(:state), :class => 'hidden-xs' %>
      <%= make_not_available_column Weakness.human_attribute_name(:follow_up_date), class: 'hidden-xs hidden-sm hidden-md' %>
      <%= make_not_available_column Weakness.human_attribute_name(:risk), :class => 'hidden-xs' %>
      <%= make_filterable_column Tag.model_name.human(count: 0), { :class => 'hidden-xs' }, 'tags' %>
      <%= make_not_available_column WorkPaper.model_name.human(count: 0), :class => 'hidden-xs' %>
      <th colspan="2" class="text-right"><%= link_to_search if params[:control_objective].blank? %></th>
    </tr>
  </thead>

  <tbody>
    <% @weaknesses.each do |weakness| %>
      <tr <%== 'class="text-muted"' if weakness.is_in_a_final_review? %>>
        <td><%= finding_updated_at_text weakness %></td>
        <td><%= show_review_with_close_date_as_abbr weakness.review %></td>
        <td class="hidden-xs"><%= super_truncate weakness.review.try(:plan_item).try(:project), 20 %></td>
        <td><%= show_finding_review_code_with_decription_as_abbr(weakness) %></td>
        <td class="hidden-xs"><%= super_truncate weakness.title, 20 %></td>
        <td class="hidden-xs"><%= super_truncate weakness.state_text, 19 %></td>
        <td class="hidden-xs hidden-sm hidden-md"><%= l weakness.follow_up_date, :format => :short if weakness.follow_up_date %></td>
        <td class="hidden-xs"><%= weakness.risk_text %></td>
        <td class="hidden-xs"><%= tags weakness.tags.reload %></td>
        <td class="hidden-xs"><%= t weakness.work_papers.blank? ? 'label.no' : 'label.yes' %></td>
        <td><%= link_to_show weakness %></td>
        <td><%= link_to_edit edit_weakness_path(weakness) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr />

<div class="clearfix">
  <%= paginate @weaknesses %>

  <%= link_to t('finding.download_csv'), weaknesses_path(request.query_parameters.merge(format: :csv)) %>

  <% if params[:control_objective].to_i > 0 %>
    | <%= link_to t('label.new'), new_weakness_path(
      :control_objective_item => params[:control_objective]), class: 'btn btn-primary' %> |
    <%= link_to t('weakness.see_all'), weaknesses_path %>
  <% end %>
</div>

app/views/weaknesses/new.html.erb
<%= content_for :form_actions do %>
  <%= link_to_index weaknesses_path %>
  <% if @weakness.control_objective_item %>
    | <%= link_to t('weakness.edit_control_objective'),
      edit_control_objective_item_path(@weakness.control_objective_item) %>
  <% end %>
<% end %>

<%= render 'form' %>