config/routes.rb
Rails.application.routes.draw do
  post '/touch', to: 'touch#create', as: 'touch'

  # Sessions
  get    'login',    to: 'sessions#new',     as: 'login'
  post   'sessions', to: 'sessions#create',  as: 'sessions'
  delete 'logout',   to: 'sessions#destroy', as: 'logout'

  resources :settings, only: [:index, :show, :edit, :update]

  resources :benefits

  resources :opening_interviews
  resources :closing_interviews

  resources :risk_assessments do
    member do
      get :fetch_item
      get :new_item
      get :add_items
      patch :sort_by_risk
      post :merge_to_plan
    end

    collection do
      get :auto_complete_for_business_unit
      get :auto_complete_for_business_unit_type
      get :auto_complete_for_best_practice
    end
  end

  resources :risk_assessment_templates

  resources :readings, only: [:create]

  resources :documents do
    get :download, on: :member
    get :auto_complete_for_tagging, on: :collection
  end

  resources :questionnaires do
    resources :polls, only: [:index]
  end

  namespace :polls do
    resources :questionnaires, only: [:index]
    resources :answers, only: [:index]
    resources :business_units, only: [:index]
    resources :users, only: [:index]
  end

  resources :polls do
    collection do
      get :reports
      get :auto_complete_for_business_unit
    end
  end

  resources :e_mails, only: [:index, :show]

  resources :business_unit_types

  resources :groups

  resources :tags, only: [] do
    resources :documents, only: [:index]
  end

  scope ':kind', kind: /control_objective|document|finding|news|plan_item|review/ do
    resources :tags
  end

  resources :news do
    get :auto_complete_for_tagging, on: :collection
  end

  get 'welcome', as: 'welcome', to: 'welcome#index'
  get 'execution_reports', as: 'execution_reports', to: 'execution_reports#index'

  [
    'weaknesses_by_state_execution',
    'weaknesses_report',
    'detailed_management_report',
    'planned_cost_summary',
    'reviews_with_incomplete_work_papers_report'
  ].each do |action|
    get "execution_reports/#{action}", to: "execution_reports##{action}", as: action
  end

  [
    'create_weaknesses_by_state_execution',
    'create_detailed_management_report',
    'create_planned_cost_summary',
    'create_weaknesses_report'
  ].each do |action|
    post "execution_reports/#{action}", to: "execution_reports##{action}", as: action
  end

  %w[
    tagged_findings_report
  ].each do |action|
    get "execution_reports/#{action}", to: "execution_reports##{action}"
    post "execution_reports/create_#{action}", to: "execution_reports#create_#{action}"
  end

  resources :versions, only: [:index, :show]

  resources :notifications, only: [:index, :show, :edit, :update] do
    member do
      get :confirm
    end
  end

  get 'conclusion_reports', as: 'conclusion_reports', to: 'conclusion_reports#index'
  get 'follow_up_audit', as: 'follow_up_audit', to: 'follow_up_audit#index'

  [
    'synthesis_report',
    'review_stats_report',
    'review_scores_report',
    'review_score_details_report',
    'weaknesses_by_state',
    'weaknesses_by_risk',
    'weaknesses_by_risk_and_business_unit',
    'weaknesses_by_audit_type',
    'control_objective_stats',
    'control_objective_stats_by_review',
    'benefits',
    'process_control_stats',
    'qa_indicators',
    'weaknesses_by_business_unit',
    'weaknesses_by_month',
    'weaknesses_by_risk_report',
    'weaknesses_by_user',
    'weaknesses_current_situation',
    'fixed_weaknesses_report',
    'weaknesses_graphs',
    'auto_complete_for_business_unit',
    'auto_complete_for_process_control'
  ].each do |action|
    get "conclusion_reports/#{action}",
      as: "#{action}_conclusion_reports",
      to: "conclusion_reports##{action}"
    get "follow_up_audit/#{action}",
      as: "#{action}_follow_up_audit",
      to: "follow_up_audit##{action}"
  end

  [
    'create_synthesis_report',
    'create_review_stats_report',
    'create_review_scores_report',
    'create_review_score_details_report',
    'create_weaknesses_by_state',
    'create_weaknesses_by_risk',
    'create_weaknesses_by_risk_and_business_unit',
    'create_weaknesses_by_audit_type',
    'create_control_objective_stats',
    'create_control_objective_stats_by_review',
    'create_benefits',
    'create_process_control_stats',
    'create_qa_indicators',
    'create_weaknesses_by_business_unit',
    'create_weaknesses_by_month',
    'create_weaknesses_by_risk_report',
    'create_weaknesses_by_user',
    'create_weaknesses_current_situation',
    'create_fixed_weaknesses_report'
  ].each do |action|
    post "conclusion_reports/#{action}",
      as: "#{action}_conclusion_reports",
      to: "conclusion_reports##{action}"
    post "follow_up_audit/#{action}",
      as: "#{action}_follow_up_audit",
      to: "follow_up_audit##{action}"
  end

  get 'conclusion_reports/cost_analysis',
    as: 'cost_analysis_conclusion_reports',
    to: 'conclusion_reports#cost_analysis'
  post 'conclusion_reports/create_cost_analysis',
    as: 'create_cost_analysis_conclusion_reports',
    to: 'conclusion_reports#create_cost_analysis'
  get 'conclusion_reports/cost_analysis/detailed',
    as: 'detailed_cost_analysis_conclusion_reports',
    to: 'conclusion_reports#cost_analysis',
    include_details: 1

  get 'conclusion_reports/cost_summary',
    as: 'cost_summary_conclusion_reports',
    to: 'conclusion_reports#cost_summary'
  post 'conclusion_reports/create_cost_summary',
    as: 'create_cost_summary_conclusion_reports',
    to: 'conclusion_reports#create_cost_summary'

  %w[
    follow_up_cost_analysis
    weaknesses_report
    weaknesses_evolution
    weaknesses_list
    weaknesses_brief
    tagged_findings_report
  ].each do |action|
    get "follow_up_audit/#{action}",
      as: "#{action}_follow_up_audit",
      to: "follow_up_audit##{action}"
    post "follow_up_audit/create_#{action}",
      as: "create_#{action}_follow_up_audit",
      to: "follow_up_audit#create_#{action}"
  end

  scope ':completed', completed: /complete|incomplete/ do
    resources :findings, except: [:destroy] do
      resources :costs

      get :follow_up_pdf, on: :member, to: 'findings/follow_up_pdf#show'

      collection do
        get :export_to_pdf
        get :export_to_csv
        get :auto_complete_for_tagging
        get :auto_complete_for_finding_relation
      end
    end
  end

  namespace :workflows do
    resources :users, only: [:index]
  end

  resources :workflows do
    get :export_to_pdf, on: :member

    collection do
      get :estimated_amount
      get :reviews_for_period
    end
  end

  namespace :conclusion_draft_reviews do
    resources :users, only: [:index]
  end

  resources :conclusion_draft_reviews, except: [:destroy] do
    member do
      get :export_to_pdf
      get :compose_email
      patch :send_by_email
      get :download_work_papers
      get :score_sheet
      post :create_bundle
    end

    collection do
      get :check_for_approval
      get :corrective_actions_update
    end
  end

  namespace :conclusion_final_reviews do
    resources :users, only: [:index]
  end

  resources :conclusion_final_reviews do
    member do
      get :export_to_pdf
      get :compose_email
      patch :send_by_email
      get :download_work_papers
      get :score_sheet
      post :create_bundle
    end

    get :export_list_to_pdf, on: :collection
  end

  namespace :reviews do
    resources :users, only: [:index]
  end

  resources :reviews do
    member do
      get :survey_pdf
      get :suggested_findings
      get :suggested_process_control_findings
      get :past_implemented_audited_findings
      get :weaknesses_and_oportunities
      get :download_work_papers
      get :estimated_amount
      get :excluded_control_objectives
      patch :finished_work_papers
      patch :recode_findings
      patch :recode_weaknesses_by_risk
      patch :recode_weaknesses_by_repetition_and_risk
      patch :recode_weaknesses_by_control_objective_order
      patch :reorder
      patch :reset_control_objective_name
    end

    collection do
      get :estimated_amount
      get :plan_item_refresh
      get :assignment_type_refresh
      get :plan_item_data
      get :auto_complete_for_finding
      get :auto_complete_for_best_practice
      get :auto_complete_for_process_control
      get :auto_complete_for_control_objective
      get :auto_complete_for_tagging
      get :next_identification_number
    end
  end

  namespace :weaknesses do
    resources :users, only: [:index]
  end

  resources :weaknesses, except: [:destroy] do
    resources :costs

    collection do
      get :auto_complete_for_tagging
      get :auto_complete_for_finding_relation
      get :auto_complete_for_control_objective_item
      get :auto_complete_for_weakness_template
      get :state_changed
      get :weakness_template_changed
    end

    member do
      patch :undo_reiteration
    end
  end

  resources :weakness_templates do
    get :auto_complete_for_control_objective, on: :collection
  end

  resources :control_objective_items do
    get :suggest_next_work_paper_code, on: :member

    collection do
      get :auto_complete_for_business_unit
      get :auto_complete_for_business_unit_type
    end
  end

  namespace :plans do
    resources :users, only: [:index]
  end

  resources :plans do
    resources :plan_items, only: [:new, :edit]

    member do
      get :calendar, to: 'plans/calendar#show'
      get :resources, to: 'plans/resources#show'
      get :stats, to: 'plans/stats#show'
    end

    collection do
      get :auto_complete_for_business_unit
      get :auto_complete_for_tagging
    end
  end

  resources :resource_classes

  resources :control_objectives, only: [:index, :show]

  resources :best_practices do
    resources :process_controls, only: [:new, :edit]

    resources :control_objectives, only: [] do
      get :download, on: :member, controller: 'best_practices/control_objectives'

app/models/concerns/documents/attribute_types.rb
module Documents::AttributeTypes
  extend ActiveSupport::Concern

  included do
    attribute :shared, :boolean
  end
end

app/models/concerns/documents/defaults.rb
module Documents::Defaults
  extend ActiveSupport::Concern

  included do
    after_initialize :set_defaults, if: :new_record?
  end

  private

    def set_defaults
      self.group_id        = Current.group&.id
      self.organization_id = Current.organization&.id
    end
end

app/models/concerns/documents/file_model.rb
module Documents::FileModel
  extend ActiveSupport::Concern

  included do
    after_initialize :set_organization_id_on_file_model

    belongs_to :file_model, dependent: :destroy, optional: true
    accepts_nested_attributes_for :file_model, allow_destroy: true, reject_if: :all_blank
  end

  private

    def set_organization_id_on_file_model
      file_model.organization_id = organization_id if file_model
    end
end

app/models/concerns/documents/scopes.rb
module Documents::Scopes
  extend ActiveSupport::Concern

  included do
    scope :ordered, -> { order :name }
  end

  module ClassMethods
    def search query: nil
      result = ordered

      if query.present?
        result = result.where "LOWER(#{table_name}.name) LIKE ?", "%#{query.strip}%".downcase
      end

      result
    end
  end
end

app/models/concerns/documents/search.rb
module Documents::Search
  extend ActiveSupport::Concern

  included do
    COLUMNS_FOR_SEARCH = ActiveSupport::HashWithIndifferentAccess.new(
      name: {
        column: "LOWER(#{quoted_table_name}.#{qcn('name')})", operator: 'LIKE',
        mask: "%%%s%%", conversion_method: :to_s, regexp: /.*/
      },
      description: {
        column: "LOWER(#{quoted_table_name}.#{qcn('description')})", operator: 'LIKE',
        mask: "%%%s%%", conversion_method: :to_s, regexp: /.*/
      },
      tags: {
        column: "LOWER(#{Tag.quoted_table_name}.#{Tag.qcn('name')})", operator: 'LIKE',
        mask: "%%%s%%", conversion_method: :to_s, regexp: /.*/
      }
    )
  end
end

app/models/concerns/documents/shared.rb
module Documents::Shared
  extend ActiveSupport::Concern

  included do
    before_save :mark_tags_as_shared
  end

  private

    def mark_tags_as_shared
      if shared_changed? && shared
        taggings.each do |tagging|
          tagging.tag.update! shared: true unless tagging.tag.shared
        end
      end
    end
end

app/models/concerns/documents/validation.rb
module Documents::Validation
  extend ActiveSupport::Concern

  included do
    validates :organization, :group, presence: true
    validates :name, presence: true, length: { maximum: 255 }
    validate :has_at_least_one_tag
  end

  private

    def has_at_least_one_tag
      unless taggings.reject(&:marked_for_destruction?).any?
        errors.add :tags, :empty
      end
    end
end

app/models/document.rb
class Document < ApplicationRecord
  include Auditable
  include Documents::AttributeTypes
  include Documents::Defaults
  include Documents::FileModel
  include Documents::Scopes
  include Documents::Search
  include Documents::Shared
  include Documents::Validation
  include Shareable
  include Taggable
  include Trimmer

  trimmed_fields :name

  belongs_to :group
  belongs_to :organization

  def to_s
    name
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  include AutoCompleteFor::Tagging

  respond_to :html

  before_action :auth, :load_privileges, :check_privileges
  before_action :set_tag, only: [:index]
  before_action :set_document, only: [:show, :edit, :update, :destroy, :download]
  before_action :set_title, except: [:destroy]

  def index
    build_search_conditions Document

    if @tag
      @documents = documents.includes(:tags).where(@conditions).references(:tags).order(:name).page params[:page]
    else
      @document_tags   = Tagging.grouped_with_document_count
      @documents_count = @document_tags.values.sum
    end

    respond_with @documents
  end

  def show
  end

  def new
    @document = documents.new
  end

  def edit
  end

  def create
    @document = documents.new document_params

    @document.save
    respond_with @document
  end

  def update
    update_resource @document, document_params
    respond_with @document
  end

  def destroy
    @document.destroy
    respond_with @document
  end

  def download
    flash[:allow_path] = @document.file_model&.file&.path

    redirect_to @document.file_model&.file&.url || root_url
  end

  private

    def set_document
      @document = documents.find params[:id]
    end

    def set_tag
      @tag = Tag.list.find params[:tag_id] if params[:tag_id]
    end

    def document_params
      params.require(:document).permit :name, :description, :shared, :lock_version,
        file_model_attributes: [:id, :file, :file_cache, :_destroy],
        taggings_attributes:   [:id, :tag_id, :_destroy]
    end

    def documents
      @tag ? @tag.documents.list : Document.list
    end

    def load_privileges
      @action_privileges.update(
        download: :read,
        auto_complete_for_tagging: :read
      )
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
  def link_to_download_document document, options = {}
    url   = url_from_document_file_model(document) || url_from_document_description(document)
    title = document.file_model&.identifier&.titleize || url
    icon  = document.file_model ? 'download-alt' : 'link'

    if url.present?
      default_options = {
        class: 'btn btn-default',
        title: title,
        data:  { ignore_unsaved_data: true }
      }

      link_to url, default_options.merge(options) do
        content_tag :span, nil, class: "icon glyphicon glyphicon-#{icon}"
      end
    end
  end

  def show_document_info document
    created_at_label = Document.human_attribute_name 'created_at'
    updated_at_label = Document.human_attribute_name 'updated_at'
    created_at_value = l document.created_at, format: :short
    updated_at_value = l document.updated_at, format: :short

    show_info [
      "#{created_at_label}: #{created_at_value}",
      "#{updated_at_label}: #{updated_at_value}"
    ].join("\n")
  end

  private

    def url_from_document_file_model document
      file_model = document.file_model

      if file_model && file_model.file? && file_model.file.cached?.blank?
        download_document_path document
      end
    end

    def url_from_document_description document
      url_regex = /(ftp|file|http|https):\/\/[\\\w\-.:%]+(\/\S*)?/

      document.description.to_s.match(url_regex) && $~[0]
    end
end

app/views/documents/_form.html.erb
<%= simple_form_for @document do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, input_html: { autofocus: true } %>
    <%= f.input :description %>
    <%= f.input :shared, input_html: { disabled: @document.persisted? && @document.shared } %>
    <%= f.input :lock_version, as: :hidden %>

    <%= f.simple_fields_for :file_model, file_model(f.object) do |fm_f| %>
      <div class="file-container text-right <%= 'has-error' if file_model_error f.object %>">
        <%= link_to_upload fm_f.object %>

        <% if fm_f.object.file_cache %>
          <%= fm_f.input :file_cache, as: :hidden %>
          <%= fm_f.input :file, as: :hidden, input_html: { value: nil } %>
        <% else %>
          <%= fm_f.input :file, label: false %>
        <% end %>

        <span class="help-block"><%= file_model_error f.object %></span>
      </div>
    <% end %>

    <div class="panel <%= @document.errors[:tags].blank? ? 'panel-default' : 'panel-danger' %>">
      <div class="panel-heading">
        <h3 class="panel-title">
          <%= Tag.model_name.human count: 0 %>
        </h3>
      </div>
      <div class="panel-body">
        <% @document.errors.full_messages_for(:tags).each do |error| %>
          <p class="text-danger"><%= error %></p>
        <% end %>

        <%= f.simple_fields_for :taggings do |tf| %>
          <%= render 'tagging', f: tf, kind: 'document' %>
        <% end %>

        <%= link_to_add_fields t('documents.new.tagging'), f, :taggings, 'documents/tagging' %>
      </div>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn-primary' %>
  </div>
<% end %>

app/views/documents/_list.html.erb
<table class="table table-striped table-hover">
  <caption>
    <h3>
      <%= @tag %>
      <small class="pull-right">
        <%= link_to t('label.back'), documents_path %>
      </small>
    </h3>
  </caption>
  <thead id="column_headers">
    <tr>
      <th colspan="2"></th>
      <%= make_filterable_column Document.human_attribute_name('name'), nil, 'name' %>
      <%= make_filterable_column Document.human_attribute_name('description'), { class: 'hidden-sm hidden-xs'}, 'description' %>
      <%= make_not_available_column Document.human_attribute_name('shared') %>
      <%= make_filterable_column Tag.model_name.human(count: 0), { class: 'hidden-xs' }, 'tags' %>
      <th colspan="3" class="text-right"><%= link_to_search %></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= show_document_info document %></td>
        <td><%= link_to_download_document document, class: 'btn btn-default btn-xs' %></td>
        <td><%= super_truncate document.name, 25 %></td>
        <td class="hidden-sm hidden-xs"><%= super_truncate document.description, 25 %></td>
        <td><%= t document.shared ? 'label.yes' : 'label.no' %></td>
        <td class="hidden-xs"><%= tags document.tags %></td>
        <td><%= link_to_show document %></td>
        <td><%= link_to_edit [:edit, document] %></td>
        <td><%= link_to_destroy document %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @documents %>

app/views/documents/_tag_list.html.erb
<% @document_tags.each_slice(3) do |tags| %>
  <div class="row">
    <% tags.each do |tag_data, count| %>
      <% tag_id, tag_name, tag_icon, tag_style = *tag_data %>

      <div class="col-md-4">
        <%= link_to tag_documents_path(tag_id), class: "text-#{tag_style == 'default' ? 'muted' : tag_style}" do %>
          <div class="panel panel-<%= tag_style %>">
            <div class="panel-heading">
              <h3 class="panel-title">
                <%= tag_name %>
                <span class="pull-right">
                  <span class="badge badge-<%= tag_style %>"><%= count %></span>
                </span>
              </h3>
            </div>

            <div class="panel-body text-center">
              <h4 class="icon-lg">
                <span class="glyphicon glyphicon-<%= tag_icon %>"></span>
              </h4>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

<hr>

app/views/documents/_tagging.html.erb
<%
  id = f.object.object_id
  tagging = f.object
%>
<fieldset class="tagging">
  <div class="form-inputs">
    <div class="row">
      <div class="col-md-6">
        <% if tagging.tag.blank? %>
          <%= f.input :tag_id, as: :string, label: false, input_html: {
            value: tagging.tag.to_s,
            id: "document_tagging_#{id}",
            title: t('label.search'), autocomplete: :off, autofocus: true,
            data: {
              autocomplete_params: { kind: 'document' },
              autocomplete_url: url_for([:auto_complete_for_tagging, Document]),
              autocomplete_id_target: "#hidden_tag_#{id}"
            }
          } %>
        <% else %>
          <%= f.input "document_tagging_#{id}", label: false, input_html: { value: tagging.tag.to_s, readonly: true } %>
        <% end %>
        <%= f.input :tag_id, as: :hidden, input_html: { id: "hidden_tag_#{id}" } %>
      </div>
      <div class="col-md-2">
        <div class="toggle-visibility">
          <%= link_to_remove_nested_item f %>
        </div>
      </div>
    </div>
  </div>
</fieldset>

app/views/documents/edit.html.erb
<%= render 'form' %>

<br />

<%= link_to_show @document %> |
<%= link_to_index documents_path %>

app/views/documents/index.html.erb
<%= render partial: 'shared/search', locals: {
  options: {},
  columns: @query.blank? ? Document::COLUMNS_FOR_SEARCH.keys : @columns
} %>

<% if @tag.blank? && @documents_count == 0 %>
  <%= render 'shared/empty_index', message: @query.blank? ? t('.empty_html') : t('.empty_search_html') %>
<% else %>
  <% if @documents %>
    <%= render 'list' %>
  <% else %>
    <%= render 'tag_list' %>
  <% end %>
<% end %>

<% if can? :modify, :administration_documents %>
  <%= link_to_new new_document_path, class: 'btn btn-primary' %>
<% end %>

app/views/documents/new.html.erb
<%= render 'form' %>

<br />

<%= link_to_index documents_path %>

app/views/documents/show.html.erb
<h2>
  <%= @document %>
  <span class="pull-right"><%= link_to_download_document @document %></span>
</h2>

<p>
  <strong><%= Document.human_attribute_name 'description' %></strong>:
  <%= @document.description %>
</p>

<p>
  <strong><%= Document.human_attribute_name 'created_at' %></strong>:
  <%= l @document.created_at, format: :short  %>
</p>

<p>
  <strong><%= Document.human_attribute_name 'updated_at' %></strong>:
  <%= l @document.updated_at, format: :short %>
</p>

<p>
  <strong><%= Document.human_attribute_name 'shared' %></strong>:
  <%= t @document.shared ? 'label.yes' : 'label.no' %>
</p>

<% if @document.taggings.any? %>
  <ul class="list-inline">
    <% @document.taggings.each do |tagging| %>
      <%= tagging_item tagging %>
    <% end %>
  </ul>
<% end %>

<%= link_to_edit [:edit, @document] %> |
<%= link_to_index documents_path %>