config/routes.rb
Rails.application.routes.draw do
  post '/touch', to: 'touch#create', as: 'touch'

  # Sessions
  get    'login',    to: 'sessions#new',     as: 'login'
  post   'sessions', to: 'sessions#create',  as: 'sessions'
  delete 'logout',   to: 'sessions#destroy', as: 'logout'

  resources :settings, only: [:index, :show, :edit, :update]

  resources :benefits

  resources :opening_interviews
  resources :closing_interviews

  resources :risk_assessments do
    member do
      get :fetch_item
      get :new_item
      get :add_items
      patch :sort_by_risk
      post :merge_to_plan
    end

    collection do
      get :auto_complete_for_business_unit
      get :auto_complete_for_business_unit_type
      get :auto_complete_for_best_practice
    end
  end

  resources :risk_assessment_templates

  resources :readings, only: [:create]

  resources :documents do
    get :download, on: :member
    get :auto_complete_for_tagging, on: :collection
  end

  resources :questionnaires do
    resources :polls, only: [:index]
  end

  namespace :polls do
    resources :questionnaires, only: [:index]
    resources :answers, only: [:index]
    resources :business_units, only: [:index]
    resources :users, only: [:index]
  end

  resources :polls do
    collection do
      get :reports
      get :auto_complete_for_business_unit
    end
  end

  resources :e_mails, only: [:index, :show]

  resources :business_unit_types

  resources :groups

  resources :tags, only: [] do
    resources :documents, only: [:index]
  end

  scope ':kind', kind: /control_objective|document|finding|news|plan_item|review/ do
    resources :tags
  end

  resources :news do
    get :auto_complete_for_tagging, on: :collection
  end

  get 'welcome', as: 'welcome', to: 'welcome#index'
  get 'execution_reports', as: 'execution_reports', to: 'execution_reports#index'

  [
    'weaknesses_by_state_execution',
    'weaknesses_report',
    'detailed_management_report',
    'planned_cost_summary',
    'reviews_with_incomplete_work_papers_report'
  ].each do |action|
    get "execution_reports/#{action}", to: "execution_reports##{action}", as: action
  end

  [
    'create_weaknesses_by_state_execution',
    'create_detailed_management_report',
    'create_planned_cost_summary',
    'create_weaknesses_report'
  ].each do |action|
    post "execution_reports/#{action}", to: "execution_reports##{action}", as: action
  end

  %w[
    tagged_findings_report
  ].each do |action|
    get "execution_reports/#{action}", to: "execution_reports##{action}"
    post "execution_reports/create_#{action}", to: "execution_reports#create_#{action}"
  end

  resources :versions, only: [:index, :show]

  resources :notifications, only: [:index, :show, :edit, :update] do
    member do
      get :confirm
    end
  end

  get 'conclusion_reports', as: 'conclusion_reports', to: 'conclusion_reports#index'
  get 'follow_up_audit', as: 'follow_up_audit', to: 'follow_up_audit#index'

  [
    'synthesis_report',
    'review_stats_report',
    'review_scores_report',
    'review_score_details_report',
    'weaknesses_by_state',
    'weaknesses_by_risk',
    'weaknesses_by_risk_and_business_unit',
    'weaknesses_by_audit_type',
    'control_objective_stats',
    'control_objective_stats_by_review',
    'benefits',
    'process_control_stats',
    'qa_indicators',
    'weaknesses_by_business_unit',
    'weaknesses_by_month',
    'weaknesses_by_risk_report',
    'weaknesses_by_user',
    'weaknesses_current_situation',
    'fixed_weaknesses_report',
    'weaknesses_graphs',
    'auto_complete_for_business_unit',
    'auto_complete_for_process_control'
  ].each do |action|
    get "conclusion_reports/#{action}",
      as: "#{action}_conclusion_reports",
      to: "conclusion_reports##{action}"
    get "follow_up_audit/#{action}",
      as: "#{action}_follow_up_audit",
      to: "follow_up_audit##{action}"
  end

  [
    'create_synthesis_report',
    'create_review_stats_report',
    'create_review_scores_report',
    'create_review_score_details_report',
    'create_weaknesses_by_state',
    'create_weaknesses_by_risk',
    'create_weaknesses_by_risk_and_business_unit',
    'create_weaknesses_by_audit_type',
    'create_control_objective_stats',
    'create_control_objective_stats_by_review',
    'create_benefits',
    'create_process_control_stats',
    'create_qa_indicators',
    'create_weaknesses_by_business_unit',
    'create_weaknesses_by_month',
    'create_weaknesses_by_risk_report',
    'create_weaknesses_by_user',
    'create_weaknesses_current_situation',
    'create_fixed_weaknesses_report'
  ].each do |action|
    post "conclusion_reports/#{action}",
      as: "#{action}_conclusion_reports",
      to: "conclusion_reports##{action}"
    post "follow_up_audit/#{action}",
      as: "#{action}_follow_up_audit",
      to: "follow_up_audit##{action}"
  end

  get 'conclusion_reports/cost_analysis',
    as: 'cost_analysis_conclusion_reports',
    to: 'conclusion_reports#cost_analysis'
  post 'conclusion_reports/create_cost_analysis',
    as: 'create_cost_analysis_conclusion_reports',
    to: 'conclusion_reports#create_cost_analysis'
  get 'conclusion_reports/cost_analysis/detailed',
    as: 'detailed_cost_analysis_conclusion_reports',
    to: 'conclusion_reports#cost_analysis',
    include_details: 1

  get 'conclusion_reports/cost_summary',
    as: 'cost_summary_conclusion_reports',
    to: 'conclusion_reports#cost_summary'
  post 'conclusion_reports/create_cost_summary',
    as: 'create_cost_summary_conclusion_reports',
    to: 'conclusion_reports#create_cost_summary'

  %w[
    follow_up_cost_analysis
    weaknesses_report
    weaknesses_evolution
    weaknesses_list
    weaknesses_brief
    tagged_findings_report
  ].each do |action|
    get "follow_up_audit/#{action}",
      as: "#{action}_follow_up_audit",
      to: "follow_up_audit##{action}"
    post "follow_up_audit/create_#{action}",
      as: "create_#{action}_follow_up_audit",
      to: "follow_up_audit#create_#{action}"
  end

  scope ':completed', completed: /complete|incomplete/ do
    resources :findings, except: [:destroy] do
      resources :costs

      get :follow_up_pdf, on: :member, to: 'findings/follow_up_pdf#show'

      collection do
        get :export_to_pdf
        get :export_to_csv
        get :auto_complete_for_tagging
        get :auto_complete_for_finding_relation
      end
    end
  end

  namespace :workflows do
    resources :users, only: [:index]
  end

  resources :workflows do
    get :export_to_pdf, on: :member

    collection do
      get :estimated_amount
      get :reviews_for_period
    end
  end

  namespace :conclusion_draft_reviews do
    resources :users, only: [:index]
  end

  resources :conclusion_draft_reviews, except: [:destroy] do
    member do
      get :export_to_pdf
      get :compose_email
      patch :send_by_email
      get :download_work_papers
      get :score_sheet
      post :create_bundle
    end

    collection do
      get :check_for_approval
      get :corrective_actions_update
    end
  end

  namespace :conclusion_final_reviews do
    resources :users, only: [:index]
  end

  resources :conclusion_final_reviews do
    member do
      get :export_to_pdf
      get :compose_email
      patch :send_by_email
      get :download_work_papers
      get :score_sheet
      post :create_bundle
    end

    get :export_list_to_pdf, on: :collection
  end

  namespace :reviews do
    resources :users, only: [:index]
  end

  resources :reviews do
    member do
      get :survey_pdf
      get :suggested_findings
      get :suggested_process_control_findings
      get :past_implemented_audited_findings
      get :weaknesses_and_oportunities
      get :download_work_papers
      get :estimated_amount
      get :excluded_control_objectives
      patch :finished_work_papers
      patch :recode_findings
      patch :recode_weaknesses_by_risk
      patch :recode_weaknesses_by_repetition_and_risk
      patch :recode_weaknesses_by_control_objective_order
      patch :reorder
      patch :reset_control_objective_name
    end

    collection do
      get :estimated_amount
      get :plan_item_refresh
      get :assignment_type_refresh
      get :plan_item_data
      get :auto_complete_for_finding
      get :auto_complete_for_best_practice
      get :auto_complete_for_process_control
      get :auto_complete_for_control_objective
      get :auto_complete_for_tagging
      get :next_identification_number
    end
  end

  namespace :weaknesses do
    resources :users, only: [:index]
  end

  resources :weaknesses, except: [:destroy] do
    resources :costs

    collection do
      get :auto_complete_for_tagging
      get :auto_complete_for_finding_relation
      get :auto_complete_for_control_objective_item
      get :auto_complete_for_weakness_template
      get :state_changed
      get :weakness_template_changed
    end

    member do
      patch :undo_reiteration
    end
  end

  resources :weakness_templates do
    get :auto_complete_for_control_objective, on: :collection
  end

  resources :control_objective_items do
    get :suggest_next_work_paper_code, on: :member

    collection do
      get :auto_complete_for_business_unit
      get :auto_complete_for_business_unit_type
    end
  end

  namespace :plans do
    resources :users, only: [:index]
  end

  resources :plans do
    resources :plan_items, only: [:new, :edit]

    member do
      get :calendar, to: 'plans/calendar#show'
      get :resources, to: 'plans/resources#show'
      get :stats, to: 'plans/stats#show'
    end

    collection do
      get :auto_complete_for_business_unit
      get :auto_complete_for_tagging
    end
  end

  resources :resource_classes

  resources :control_objectives, only: [:index, :show]

  resources :best_practices do
    resources :process_controls, only: [:new, :edit]

    resources :control_objectives, only: [] do
      get :download, on: :member, controller: 'best_practices/control_objectives'

app/models/concerns/plans/clone.rb
module Plans::Clone
  extend ActiveSupport::Concern

  def clone_from(other)
    diff_in_years = diff_in_years_for period, other.period

    other.plan_items.each do |plan_item|
      attributes = plan_item_attributes_for plan_item, diff_in_years

      plan_items.build attributes
    end

    self.allow_overload    = true
    self.allow_duplication = true
  end

  private

    def diff_in_years_for period, other_period
      period ? (period.start.year - other_period.start.year).years : 0
    end

    def plan_item_attributes_for plan_item, diff_in_years
      attributes = plan_item.attributes.merge(
        'id'                               => nil,
        'resource_utilizations_attributes' => resource_utilizations_attributes_for(plan_item)
      ).with_indifferent_access

      complete_start_and_end_attributes attributes, diff_in_years
    end

    def resource_utilizations_attributes_for plan_item
      plan_item.resource_utilizations.map do |resource_utilization|
        resource_utilization.attributes.merge 'id' => nil
      end
    end

    def complete_start_and_end_attributes attributes, diff_in_years
      if attributes[:start]
        item_start = attributes[:start] = attributes[:start] + diff_in_years
      end

      if attributes[:end]
        item_end = attributes[:end] = attributes[:end] + diff_in_years
      end

      if period
        attributes[:start] = period.start unless period.contains? item_start
        attributes[:end]   = period.end   unless period.contains? item_end
      end

      attributes
    end
end

app/models/concerns/plans/costs.rb
module Plans::Costs
  extend ActiveSupport::Concern

  def estimated_amount business_unit_type = nil
    items = plan_items.for_business_unit_type business_unit_type

    items.inject 0.0 do |sum, plan_item|
      sum + plan_item.resource_utilizations.to_a.sum(&:cost)
    end
  end

  def cost
    plan_items.to_a.sum &:cost
  end
end

app/models/concerns/plans/destroy_validation.rb
module Plans::DestroyValidation
  extend ActiveSupport::Concern

  included do
    before_destroy :check_if_can_be_destroyed
  end

  def can_be_destroyed?
    if plan_items.all?(&:can_be_destroyed?)
      true
    else
      _errors = plan_items.map do |pi|
        pi.errors.full_messages.join APP_ENUM_SEPARATOR
      end

      errors.add :base, _errors.reject(&:blank?).join(APP_ENUM_SEPARATOR)

      false
    end
  end

  private

    def check_if_can_be_destroyed
      throw :abort unless can_be_destroyed?
    end
end

app/controllers/plans/calendar_controller.rb
class Plans::CalendarController < ApplicationController
  respond_to :html

  before_action :auth, :check_privileges
  before_action :set_title, :set_plan

  def show
  end

  private

    def set_plan
      @plan = Plan.list.find params[:id]
    end
end

app/controllers/plans/resources_controller.rb
class Plans::ResourcesController < ApplicationController
  respond_to :html

  before_action :auth, :check_privileges
  before_action :set_title, :set_plan

  def show
    respond_to do |format|
      format.html
      format.pdf  { redirect_to pdf.relative_path }
    end
  end

  private

    def set_plan
      @plan = Plan.list.find params[:id]
      @human_resource_utilizations = @plan.
        resource_utilizations.
        joins(:user, :plan_item).
        includes(:user, :plan_item).
        group_by(&:resource_id)
    end

    def pdf
      PlanResourcesPdf.create(
        title: t('.title'),
        plan: @plan,
        human_resource_utilizations: @human_resource_utilizations,
        current_organization: current_organization
      )
    end
end

app/controllers/plans/stats_controller.rb
class Plans::StatsController < ApplicationController
  respond_to :html

  before_action :auth, :check_privileges
  before_action :set_title, :set_plan

  def show
    @until = Timeliness.parse params[:until], :date if params[:until].present?
  end

  private

    def set_plan
      @plan = Plan.list.includes(
        plan_items: { review: :conclusion_final_review }
      ).find params[:id]
    end
end

app/controllers/plans/users_controller.rb
class Plans::UsersController < ApplicationController
  include Users::Searches

  def index
    render template: 'users/index'
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  include AutoCompleteFor::BusinessUnit
  include AutoCompleteFor::Tagging

  respond_to :html, :js

  before_action :auth, :load_privileges, :check_privileges
  before_action :set_business_unit_type, only: [:show, :new, :edit]
  before_action :set_plan, only: [:show, :edit, :update, :destroy, :export_to_pdf]
  before_action :set_plan_clone, only: [:new, :create]
  before_action :set_title, except: [:destroy]

  # * GET /plans
  def index
    @plans = Plan.list.includes(:period).references(:period).order(
      Arel.sql "#{Period.quoted_table_name}.#{Period.qcn('start')} DESC"
    ).page params[:page]
  end

  # * GET /plans/1
  def show
    respond_to do |format|
      format.html
      format.js
      format.pdf  { redirect_to plan_pdf_path }
    end
  end

  # * GET /plans/new
  def new
    @plan = Plan.new

    @plan.clone_from @plan_clone if @plan_clone
  end

  # * GET /plans/1/edit
  def edit
  end

  # * POST /plans
  def create
    @plan = Plan.list.new plan_params

    @plan.clone_from @plan_clone if @plan_clone

    @plan.save

    respond_with @plan, location: -> {
      if @plan.persisted?
        edit_plan_url @plan, business_unit_type: params[:business_unit_type]
      end
    }
  end

  # * PATCH /plans/1
  def update
    update_resource @plan, plan_params

    respond_with @plan, location: edit_plan_url(@plan, business_unit_type: params[:business_unit_type])
  end

  # * DELETE /plans/1
  def destroy
    @plan.destroy

    respond_with @plan, location: plans_url
  end

  private

    def plan_params
      params.require(:plan).permit(
        :period_id, :allow_overload, :allow_duplication,
        :lock_version, plan_items_attributes: [
          :id, :project, :start, :end, :order_number, :risk_exposure, :scope,
          :business_unit_id, :_destroy,
          resource_utilizations_attributes: [
            :id, :resource_id, :resource_type, :units, :_destroy
          ],
          taggings_attributes: [
            :id, :tag_id, :_destroy
          ]
        ]
      )
    end

    def set_business_unit_type
      if params[:business_unit_type].to_i > 0
        @business_unit_type = BusinessUnitType.find params[:business_unit_type]
      end
    end

    def set_plan
      @plan = Plan.list.includes(
        plan_items: [
          :resource_utilizations, :business_unit,
          { review: :conclusion_final_review }
        ]
      ).find(params[:id])
    end

    def set_plan_clone
      @plan_clone = Plan.list.find_by id: params[:clone_from]
    end

    def plan_pdf_path
      @plan.to_pdf current_organization,
        include_details: params[:include_details].present?,
        business_unit_type: @business_unit_type

      @plan.relative_pdf_path
    end

    def load_privileges
      @action_privileges.update(
        export_to_pdf: :read,
        auto_complete_for_business_unit: :read,
        auto_complete_for_tagging: :read
      )
    end
end

app/helpers/plans/calendar_helper.rb
module Plans::CalendarHelper
  def month_in_weeks month
    cursor = month.at_beginning_of_month.at_beginning_of_week.to_date
    ending = month.at_end_of_month.at_beginning_of_week.to_date
    weeks  = []

    while cursor <= ending
      weeks << cursor.all_week

      cursor = cursor.advance weeks: 1
    end

    weeks
  end

  def business_unit_with_plan_items_in_week? business_unit, week
    @plan.plan_items.any? do |pi|
      if pi.business_unit_id == business_unit.id
        week.overlaps? (pi.start)..(pi.end)
      end
    end
  end
end

app/helpers/plans/resources_helper.rb
module Plans::ResourcesHelper
end

app/views/plans/_business_unit_type_plan_items.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4 class="panel-title">
      <%= business_unit_type&.name || t('plans.without_business_unit_type') %>
      <% unless plan_status_date.today? %>
        <small class="pull-right">
          <span class="glyphicon glyphicon-calendar"></span>
          <%= l plan_status_date.to_date %>
        </small>
      <% end %>
    </h4>
  </div>

  <div class="panel-body">
    <div class="table-responsive">
      <table class="table table-striped table-condensed table-hover">
        <thead>
          <tr>
            <th></th>
            <th><%= PlanItem.human_attribute_name 'order_number' %></th>
            <th><%= BusinessUnit.model_name.human %></th>
            <th><%= PlanItem.human_attribute_name 'project' %></th>
            <% if SHOW_REVIEW_EXTRA_ATTRIBUTES %>
              <th><%= PlanItem.human_attribute_name 'scope' %></th>
              <th><%= PlanItem.human_attribute_name 'risk_exposure' %></th>
            <% end %>
            <th><%= Tag.model_name.human count: 0 %></th>
            <th><%= PlanItem.human_attribute_name 'start' %></th>
            <th><%= PlanItem.human_attribute_name 'end' %></th>
          </tr>
        </thead>
        <tbody>
          <% plan_items.each do |plan_item| %>
            <tr>
              <td><%= show_plan_item_info(plan_item) %></td>
              <td><%= plan_item.order_number %></td>
              <td><%= plan_item.business_unit&.name %></td>
              <td><%= plan_item.project %></td>
              <% if SHOW_REVIEW_EXTRA_ATTRIBUTES %>
                <td><%= plan_item.scope %></td>
                <td><%= plan_item.risk_exposure %></td>
              <% end %>
              <td><%= tags plan_item.tags %></td>
              <td><%= l plan_item.start, format: :minimal %></td>
              <td><%= l plan_item.end, format: :minimal %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <% if show_resource_utilization && plan_items.any? { |pi| pi.resource_utilizations.present? } %>
      <h4><%= t 'plans.pdf.resource_utilization' %></h4>

      <% plan_items.each do |plan_item| %>
        <% if plan_item.resource_utilizations.present? %>
          <div class="table-responsive">
            <table class="table table-striped table-condensed table-hover">
              <caption>
                <h5>
                  (<%= plan_item.order_number %>)
                  <%= plan_item.project %>
                  (<%= plan_item.business_unit&.name %>)
                </h5>
              </caption>

              <thead>
                <tr>
                  <th><%= ResourceUtilization.human_attribute_name 'resource' %></th>
                  <th><%= ResourceUtilization.human_attribute_name 'units' %></th>
                </tr>
              </thead>
              <tbody>
                <% plan_item.resource_utilizations.each do |ru| %>
                  <tr>
                    <td><%= ru.resource.resource_name %></td>
                    <td><%= ru.units %></td>
                  </tr>
                <% end %>
                <tr>
                  <td></td>
                  <td><strong><%= '%.2f' % plan_item.units %></strong></td>
                </tr>
              </tbody>
            </table>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/plans/_plan_item.html.erb
<% id    = f.object.object_id %>
<% fetch = should_fetch_resources_for? f.object %>

<fieldset class="plan_item">
  <div class="row">
    <div class="col-md-1">
      <div class="media">
        <div class="pull-left">
          <%= show_plan_item_info(f.object) %>
        </div>
        <div class="pull-left">
          <%= link_to_fetch_hide id, fetch ? :fetch : :show %>
        </div>
        <div class="media-body">
          <%= f.input :order_number, as: :string, label: false,
            input_html: { class: 'sort_number', readonly: true } %>
        </div>
      </div>
    </div>
    <div class="col-md-<%= SHOW_REVIEW_EXTRA_ATTRIBUTES ? 2 : 3 %>">
      <% unless f.object.business_unit %>
        <%= f.input :business_unit_id, as: :string, label: false, input_html: {
          name: 'plan_item[business_unit_data]', id: "plan_item_business_unit_#{id}",
          title: t('label.search'),
          autofocus: true, data: {
            autocomplete_params: ({ business_unit_type_id: @business_unit_type.id } if @business_unit_type),
            autocomplete_url: auto_complete_for_business_unit_plans_path,
            autocomplete_id_target: "#hidden_business_unit_id_#{id}"
          }
        } %>
      <% else %>
        <%= f.input "plan_item_business_unit_#{id}", label: false, input_html: {
          value: f.object.business_unit.name, disabled: true } %>
      <% end %>
      <%= f.input :business_unit_id, as: :hidden, input_html: {
        value: f.object.business_unit_id, id: "hidden_business_unit_id_#{id}" } %>
    </div>
    <div class="col-md-<%= SHOW_REVIEW_EXTRA_ATTRIBUTES ? 2 : 4 %>">
      <%= f.input :project, label: false, input_html: { maxlength: 255 } %>
    </div>
    <% if SHOW_REVIEW_EXTRA_ATTRIBUTES %>
      <div class="col-md-2">
        <%= f.input :scope, collection: review_scope_options, label: false, prompt: true %>
      </div>
      <div class="col-md-2">
        <%= f.input :risk_exposure, collection: review_risk_exposure_options, label: false, prompt: true %>
      </div>
    <% end %>
    <div class="col-md-<%= SHOW_REVIEW_EXTRA_ATTRIBUTES ? 2 : 3 %>">
      <div class="row">
        <div class="col-md-6">
          <%= f.input :start, as: :date_picker, label: false %>
        </div>
        <div class="col-md-6">
          <%= f.input :end, as: :date_picker, label: false %>
        </div>
      </div>
    </div>
    <div class="col-md-1">
      <div class="toggle-visibility">
        <%= f.input :id, as: :hidden %>
        <%= link_to_insert_field f %>
        <span class="text-muted">|</span>
        <% unless f.object.try(:review) %>
          <%= link_to_remove_nested_item f %>
          <span class="text-muted">|</span>
        <% end %>
        <%= link_to_move %>
      </div>
    </div>
  </div>

  <div class="nested hidden">
    <div class="row nested">
      <div class="col-md-8">
        <h5><strong><%= ResourceUtilization.human_attribute_name 'resource' %></strong></h5>
      </div>
      <div class="col-md-3">
        <h5><strong><%= ResourceUtilization.human_attribute_name 'units' %></strong></h5>
      </div>
    </div>

    <div class="hidden" data-container-id="<%= id %>" data-index="<%= f.index %>" data-url="<%= plan_item_path f.object %>">
      <% if fetch %>
        <div class="alert alert-warning"><%= t 'navigation.loading' %></div>
      <% else %>
        <%= render 'plan_items/form', plan_item: f.object, index: f.index %>
      <% end %>
    </div>

    <p class="nested">
      <%= link_to_add_fields(
        t('.add_material_resource_utilization'),
        f, :resource_utilizations, 'plan_items/material_resource_utilization', {
          insert_into: "#material_resource_utilizations_#{id}",
          association: 'material_resource_utilizations'
        }
      ) %>
      <%= link_to_add_fields(
        t('.add_human_resource_utilization'),
        f, :resource_utilizations, 'plan_items/human_resource_utilization', {
          insert_into: "#human_resource_utilizations_#{id}",
          association: 'human_resource_utilizations'
        }
      ) %>
      <%= link_to_add_fields(
        t('.add_tagging'),
        f, :taggings, 'plan_items/tagging', {
          insert_into: "#tags_#{id}",
          association: 'taggings'
        }
      ) %>
    </p>
  </div>
</fieldset>

app/views/plans/edit.html.erb
<%= content_for :form_actions do %>
  <%= link_to_show @plan %> |
  <%= link_to_calendar [:calendar, @plan] %> |
  <%= link_to_stats [:stats, @plan, until: Time.zone.today.to_s(:db)] %> |
  <%= link_to_index plans_path %> |
  <%= render 'shared/downloads', links: plan_download_options, right: true %>
<% end %>

<%= render 'form' %>

app/views/plans/index.html.erb
<table class="table table-condensed table-striped table-hover">
  <thead>
    <tr>
      <th><%= Period.model_name.human %></th>
      <th class="hidden-xs"><%= Period.human_attribute_name 'start' %></th>
      <th class="hidden-xs"><%= Period.human_attribute_name 'end' %></th>
      <th colspan="7"></th>
    </tr>
  </thead>

  <tbody>
    <% @plans.each do |plan| %>
      <tr>
        <td><%= show_period_with_dates_as_abbr plan.period %></td>
        <td class="hidden-xs"><%= l plan.period.start, format: :short %></td>
        <td class="hidden-xs"><%= l plan.period.end, format: :short %></td>
        <td class="hidden-xs"><%= link_to_calendar [:calendar, plan] %></td>
        <td class="hidden-xs"><%= link_to_resources [:resources, plan] %></td>
        <td class="hidden-xs"><%= link_to_stats [:stats, plan, until: Time.zone.today.to_s(:db)] %></td>
        <td class="hidden-xs"><%= link_to_clone new_plan_path(clone_from: plan.id) %></td>
        <td><%= link_to_show plan %></td>
        <td><%= link_to_edit [:edit, plan] %></td>
        <td><%= link_to_destroy plan if plan.can_be_destroyed? %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr />

<%= paginate @plans %>
<%= link_to_new new_plan_path, class: 'btn btn-primary' %>

app/views/plans/new.html.erb
<%= content_for :form_actions do %>
  <%= link_to_index plans_path %>
<% end %>

<%= render 'form' %>

app/views/plans/show.html.erb
<%= render 'header' %>

<% plan_business_unit_type_list.each do |business_unit_type, plan_items| %>
  <% if plan_items.any? %>
    <%= render 'business_unit_type_plan_items', {
      business_unit_type: business_unit_type,
      plan_items: plan_items,
      show_resource_utilization: true
    } %>
  <% end %>
<% end %>

<hr>

<div>
  <%= link_to_edit [:edit, @plan] %> |
  <%= link_to_calendar [:calendar, @plan] %> |
  <%= link_to_stats [:stats, @plan, until: Time.zone.today.to_s(:db)] %> |
  <%= link_to_index plans_path %> |
  <%= render('shared/downloads',
    right: true,
    links: [
      link_to(
        t('plans.download_global_plan'),
        [@plan, _ts: Time.now.to_i, format: :pdf]
      ),
      link_to(
        t('plans.download_detailed_plan'),
        [@plan, include_details: 1, _ts: Time.now.to_i, format: :pdf]
      )
    ]
  ) %>
</div>

app/views/plans/show.js.erb
+function () {
  $('#planned-items').
    html('<%= j render_business_unit_type_plan_items %>').
    find('.panel').
    effect('highlight')

  setTimeout(function () { location.hash = 'planned-items' })
}()